// Generated by scripts/generate-contract-schemas.mjs from domain/contracts.ts.
import { z } from "zod";
import { ConfidenceSchema, ContentHashSchema, EntityIdSchema, SourceClassSchema } from "./contracts.js";

export const JsonValueSchema: z.ZodType<unknown> = z.lazy(() =>
  z.union([z.null(), z.boolean(), z.number().finite(), z.string(), z.array(JsonValueSchema), z.record(z.string(), JsonValueSchema)]),
);
const strictObject = <T extends z.core.$ZodLooseShape>(shape: T) => z.strictObject(shape);

export const ConcernMaterialitySchema: z.ZodType = z.lazy(() => z.union([z.literal("blocking-now"), z.literal("material-soon"), z.literal("deferable")]));

export const ConcernActivationReasonSchema: z.ZodType = z.lazy(() => strictObject({
  "kind": z.union([z.literal("requirement-delta"), z.literal("scenario-delta"), z.literal("relevance-discovery"), z.literal("planning-surprise"), z.literal("constraint-delta"), z.literal("surface-added"), z.literal("scale-signal"), z.literal("pattern-friction"), z.literal("decision-trigger"), z.literal("research"), z.literal("user-request"), z.literal("inference")]),
  "subjectIds": z.array(z.union([EntityIdSchema, z.string()])),
  "explanation": z.string(),
  "causalOrigin": CausalOriginSchema
}));

export const DecisionDeferralSchema: z.ZodType = z.lazy(() => strictObject({
  "rationale": z.string(),
  "preserveOptionality": z.array(z.string()),
  "forbiddenCommitments": z.array(z.string()),
  "reconsiderWhen": z.array(AuthorityReconsiderTriggerSchema),
  "reviewBy": z.string().optional()
}));

export const ArchitectureConcernSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "key": z.string(),
  "title": z.string(),
  "question": z.string(),
  "scope": SelectorExprSchema,
  "sourceClass": SourceClassSchema,
  "status": z.union([z.literal("candidate"), z.literal("active"), z.literal("deferred"), z.literal("resolved"), z.literal("dismissed"), z.literal("superseded")]),
  "materiality": ConcernMaterialitySchema,
  "activationReasons": z.array(ConcernActivationReasonSchema),
  "relatedConceptIds": z.array(EntityIdSchema),
  "relatedRequirementIds": z.array(EntityIdSchema),
  "relevanceClosureId": EntityIdSchema.optional(),
  "decisionIds": z.array(EntityIdSchema),
  "deferral": DecisionDeferralSchema.optional(),
  "evidence": z.array(EvidenceRefSchema),
  "semanticHash": ContentHashSchema
}));

export const DecisionConsequenceSchema: z.ZodType = z.lazy(() => strictObject({
  "kind": z.union([z.literal("activate-governance"), z.literal("deactivate-governance"), z.literal("introduce-constraint"), z.literal("retire-constraint"), z.literal("select-technology"), z.literal("deprecate-technology"), z.literal("require-migration"), z.literal("activate-concern"), z.literal("constrain-decision"), z.literal("advisory")]),
  "targetId": EntityIdSchema.optional(),
  "scope": SelectorExprSchema.optional(),
  "payload": z.record(z.string(), JsonValueSchema).optional(),
  "explanation": z.string()
}));

export const AppliedPreferenceRefSchema: z.ZodType = z.lazy(() => strictObject({
  "key": z.string(),
  "scope": z.union([z.literal("user"), z.literal("organization"), z.literal("project")]),
  "semanticHash": ContentHashSchema,
  "influence": z.string()
}));

export const ArchitectureDecisionSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "key": z.string(),
  "concernId": EntityIdSchema,
  "title": z.string(),
  "decision": z.string(),
  "selectedOptionKey": z.string(),
  "scope": SelectorExprSchema,
  "lifecycle": z.union([z.literal("active"), z.literal("superseded"), z.literal("retired")]),
  "authorityRecordId": EntityIdSchema,
  "governanceBasis": z.array(GovernanceBasisSchema),
  "consequences": z.array(DecisionConsequenceSchema),
  "appliedPreferences": z.array(AppliedPreferenceRefSchema),
  "supersedesDecisionIds": z.array(EntityIdSchema),
  "migrationId": EntityIdSchema.optional(),
  "semanticHash": ContentHashSchema
}));

export const DecisionOptionSchema: z.ZodType = z.lazy(() => strictObject({
  "key": z.string(),
  "title": z.string(),
  "description": z.string(),
  "hardConstraintStatus": z.union([z.literal("passes"), z.literal("fails"), z.literal("unknown")]),
  "tradeoffs": z.array(z.string()),
  "evidence": z.array(EvidenceRefSchema),
  "preferenceFit": z.array(AppliedPreferenceRefSchema)
}));

export const DecisionEvaluationSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "concernId": EntityIdSchema,
  "scope": SelectorExprSchema,
  "options": z.array(DecisionOptionSchema),
  "eliminatedOptionKeys": z.array(z.string()),
  "recommendedOptionKey": z.string().optional(),
  "outcome": z.union([z.literal("recommended"), z.literal("contested"), z.literal("insufficient-evidence")]),
  "hardConstraints": z.array(EntityIdSchema),
  "preferenceSnapshotHash": ContentHashSchema,
  "researchEvidenceIds": z.array(EntityIdSchema),
  "unknowns": z.array(z.string()),
  "evaluatedAt": z.string(),
  "semanticHash": ContentHashSchema
}));

export const DecisionValidityAssessmentSchema: z.ZodType = z.lazy(() => strictObject({
  "decisionId": EntityIdSchema,
  "scope": SelectorExprSchema,
  "state": z.union([z.literal("valid"), z.literal("suspect"), z.literal("contested"), z.literal("invalid-for-scope")]),
  "firedTriggers": z.array(AuthorityReconsiderTriggerSchema),
  "invalidatedAssumptions": z.array(z.string()),
  "staleEvidenceIds": z.array(EntityIdSchema),
  "blocksCurrentChange": z.boolean(),
  "explanation": z.string()
}));

export const DeveloperPreferenceSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "key": z.string(),
  "scope": z.union([z.literal("user"), z.literal("organization"), z.literal("project")]),
  "selector": SelectorExprSchema,
  "strength": z.union([z.literal("prefer"), z.literal("strongly-prefer"), z.literal("avoid")]),
  "statement": z.string(),
  "rationale": z.string().optional(),
  "status": z.union([z.literal("active"), z.literal("retired")]),
  "sourceClass": SourceClassSchema,
  "semanticHash": ContentHashSchema
}));

export const GovernanceBasisSchema: z.ZodType = z.lazy(() => z.union([strictObject({
  "kind": z.literal("architecture-decision"),
  "decisionId": EntityIdSchema
}), strictObject({
  "kind": z.literal("hard-constraint"),
  "conceptId": EntityIdSchema
}), strictObject({
  "kind": z.literal("adopted-standard"),
  "authorityRecordId": EntityIdSchema
}), strictObject({
  "kind": z.literal("migration-overlay"),
  "migrationId": EntityIdSchema
}), strictObject({
  "kind": z.literal("host-safety"),
  "key": z.string()
}), strictObject({
  "kind": z.literal("active-lens"),
  "lensId": EntityIdSchema
})]));

export const EvidenceRefSchema: z.ZodType = z.lazy(() => strictObject({
  "evidenceId": EntityIdSchema,
  "stance": z.union([z.literal("supports"), z.literal("contradicts"), z.literal("context")]),
  "weight": z.number().finite().optional()
}));

export const CausalOriginSchema: z.ZodType = z.lazy(() => strictObject({
  "kind": z.union([z.literal("pre-projector"), z.literal("human"), z.literal("deterministic-observation"), z.literal("model-inference"), z.literal("semantic-resolution"), z.literal("relevance-analysis"), z.literal("planning-surprise"), z.literal("lens-transform"), z.literal("plan"), z.literal("external")]),
  "causedByLensId": EntityIdSchema.optional(),
  "causedByRuleId": EntityIdSchema.optional(),
  "causedByTransformId": z.string().optional(),
  "causedBySemanticChangeId": EntityIdSchema.optional(),
  "causedByRelevanceClosureId": EntityIdSchema.optional(),
  "causedByPlanningSurpriseId": EntityIdSchema.optional(),
  "causedByPlanId": EntityIdSchema.optional(),
  "causedByPacketId": EntityIdSchema.optional()
}));

export const SemanticSignatureSchema: z.ZodType = z.lazy(() => strictObject({
  "hash": ContentHashSchema,
  "profileId": z.string(),
  "profileVersion": z.string(),
  "scope": z.string(),
  "assurance": z.union([z.literal("exact"), z.literal("validated"), z.literal("heuristic")]),
  "evidenceIds": z.array(EntityIdSchema)
}));

export const LineageRecordSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "kind": z.union([z.literal("move"), z.literal("split"), z.literal("merge"), z.literal("replace"), z.literal("delete")]),
  "fromIds": z.array(EntityIdSchema),
  "toIds": z.array(EntityIdSchema),
  "reason": z.string(),
  "stateDigest": ContentHashSchema
}).superRefine((value, context) => {
  const issue = (message: string) => context.addIssue({ code: "custom", message });
  if (new Set(value.fromIds).size !== value.fromIds.length || new Set(value.toIds).size !== value.toIds.length) issue("lineage endpoints must be unique");
  if (value.fromIds.length === 0) issue("lineage requires at least one source");
  if (value.kind === "move" && (value.fromIds.length !== 1 || value.toIds.length !== 1)) issue("move lineage requires exactly one source and destination");
  if (value.kind === "split" && value.toIds.length < 2) issue("split lineage requires at least two destinations");
  if (value.kind === "merge" && (value.fromIds.length < 2 || value.toIds.length !== 1)) issue("merge lineage requires at least two sources and one destination");
  if (value.kind === "replace" && value.toIds.length === 0) issue("replace lineage requires at least one destination");
  if (value.kind === "delete" && value.toIds.length !== 0) issue("delete lineage cannot have destinations");
}));

export const TombstoneSchema: z.ZodType = z.lazy(() => strictObject({
  "entityId": EntityIdSchema,
  "deletedAtRevision": z.number().finite(),
  "lastSemanticHash": ContentHashSchema,
  "replacementIds": z.array(EntityIdSchema),
  "reason": z.string()
}));

export const ConceptSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "key": z.string(),
  "kind": z.union([z.literal("capability"), z.literal("behavior"), z.literal("invariant"), z.literal("decision"), z.literal("ownership"), z.literal("obligation"), z.literal("data"), z.literal("interface"), z.literal("event"), z.literal("command"), z.literal("policy"), z.literal("read-model"), z.literal("contract"), z.literal("assumption"), z.literal("migration"), z.literal("constraint")]),
  "name": z.string(),
  "aliases": z.array(z.string()),
  "statement": z.string(),
  "status": z.union([z.literal("candidate"), z.literal("active"), z.literal("deprecated"), z.literal("rejected")]),
  "sourceClass": SourceClassSchema,
  "confidence": ConfidenceSchema,
  "tags": z.array(z.string()),
  "evidence": z.array(EvidenceRefSchema),
  "discoveryHash": ContentHashSchema,
  "semanticHash": ContentHashSchema
}));

export const RelationTypeSchema: z.ZodType = z.lazy(() => z.union([z.literal("realizes"), z.literal("requires"), z.literal("constrains"), z.literal("depends-on"), z.literal("has-requirement"), z.literal("demonstrated-by"), z.literal("produces"), z.literal("consumes"), z.literal("triggers"), z.literal("governed-by"), z.literal("applies-to"), z.literal("generates"), z.literal("documents"), z.literal("verifies"), z.literal("deploys-to"), z.literal("publishes-to"), z.literal("observes"), z.literal("owns"), z.literal("incompatible-with"), z.literal("derived-from"), z.literal("supersedes"), z.literal("exception-to"), z.literal("variant-of")]));

export const RelationSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "fromId": EntityIdSchema,
  "toId": EntityIdSchema,
  "type": RelationTypeSchema,
  "sourceClass": SourceClassSchema,
  "confidence": ConfidenceSchema,
  "evidence": z.array(EvidenceRefSchema),
  "active": z.boolean(),
  "semanticHash": ContentHashSchema
}));

export const IntentOriginRefSchema: z.ZodType = z.lazy(() => strictObject({
  "kind": z.union([z.literal("user-request"), z.literal("linear"), z.literal("github-issue"), z.literal("document"), z.literal("external")]),
  "locator": z.string(),
  "contentHash": ContentHashSchema.optional(),
  "description": z.string().optional()
}));

export const RequirementSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "key": z.string(),
  "title": z.string(),
  "aliases": z.array(z.string()),
  "statement": z.string(),
  "status": z.union([z.literal("candidate"), z.literal("active"), z.literal("deprecated"), z.literal("rejected"), z.literal("superseded")]),
  "sourceClass": SourceClassSchema,
  "scope": SelectorExprSchema,
  "origin": z.array(IntentOriginRefSchema),
  "evidence": z.array(EvidenceRefSchema),
  "discoveryHash": ContentHashSchema,
  "semanticHash": ContentHashSchema
}));

export const BehavioralScenarioStepSchema: z.ZodType = z.lazy(() => strictObject({
  "role": z.union([z.literal("precondition"), z.literal("trigger"), z.literal("expected-outcome"), z.literal("forbidden-outcome")]),
  "statement": z.string()
}));

export const BehavioralScenarioSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "key": z.string(),
  "title": z.string(),
  "aliases": z.array(z.string()),
  "status": z.union([z.literal("candidate"), z.literal("active"), z.literal("deprecated"), z.literal("rejected"), z.literal("superseded")]),
  "sourceClass": SourceClassSchema,
  "scope": SelectorExprSchema,
  "steps": z.array(BehavioralScenarioStepSchema),
  "evidence": z.array(EvidenceRefSchema),
  "discoveryHash": ContentHashSchema,
  "semanticHash": ContentHashSchema
}));

export const RepresentationTargetSchema: z.ZodType = z.lazy(() => z.union([z.literal("human-technical"), z.literal("behavior-spec"), z.literal("agent-context"), z.literal("machine-invariant")]));

export const PreservationDimensionSchema: z.ZodType = z.lazy(() => z.union([z.literal("normative-force"), z.literal("negation"), z.literal("scope"), z.literal("quantifier-cardinality"), z.literal("logical-connective"), z.literal("condition-guard"), z.literal("exception"), z.literal("dependency-order"), z.literal("behavior-step-role"), z.literal("concept-identity"), z.literal("identifier-literal")]));

export const SemanticPreservationFingerprintSchema: z.ZodType = z.lazy(() => strictObject({
  "sourceSemanticHash": ContentHashSchema,
  "profileId": EntityIdSchema,
  "profileVersion": z.string(),
  "protectedDimensions": z.array(PreservationDimensionSchema),
  "dimensionHashes": z.partialRecord(z.union([z.literal("normative-force"), z.literal("negation"), z.literal("scope"), z.literal("quantifier-cardinality"), z.literal("logical-connective"), z.literal("condition-guard"), z.literal("exception"), z.literal("dependency-order"), z.literal("behavior-step-role"), z.literal("concept-identity"), z.literal("identifier-literal")]), ContentHashSchema),
  "dimensionAssurance": z.partialRecord(z.union([z.literal("normative-force"), z.literal("negation"), z.literal("scope"), z.literal("quantifier-cardinality"), z.literal("logical-connective"), z.literal("condition-guard"), z.literal("exception"), z.literal("dependency-order"), z.literal("behavior-step-role"), z.literal("concept-identity"), z.literal("identifier-literal")]), z.union([z.literal("exact"), z.literal("validated"), z.literal("heuristic")])),
  "unsupportedDimensions": z.array(PreservationDimensionSchema),
  "assurance": z.union([z.literal("exact"), z.literal("validated"), z.literal("heuristic")]),
  "evidenceIds": z.array(EntityIdSchema),
  "semanticHash": ContentHashSchema
}));

export const RepresentationStyleRuleSchema: z.ZodType = z.lazy(() => strictObject({
  "key": z.string(),
  "kind": z.union([z.literal("terminology"), z.literal("sentence-structure"), z.literal("active-voice"), z.literal("condition-order"), z.literal("scenario-structure"), z.literal("paragraph-structure"), z.literal("word-choice"), z.literal("punctuation"), z.literal("abbreviation"), z.literal("narration"), z.literal("filler-removal"), z.literal("token-optimization"), z.literal("literal-preservation")]),
  "parameters": z.record(z.string(), JsonValueSchema),
  "blocking": z.boolean()
}));

export const SemanticRepresentationProfileSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "key": z.string(),
  "version": z.string(),
  "status": z.union([z.literal("active"), z.literal("deprecated"), z.literal("retired")]),
  "target": RepresentationTargetSchema,
  "selector": SelectorExprSchema,
  "optimization": z.union([z.literal("clarity-first"), z.literal("token-first"), z.literal("machine-first")]),
  "protectedDimensions": z.array(PreservationDimensionSchema),
  "styleRules": z.array(RepresentationStyleRuleSchema),
  "generatorId": z.string(),
  "validatorIds": z.array(z.string()),
  "tokenizerProfileId": z.string().optional(),
  "fallbackProfileId": EntityIdSchema.optional(),
  "semanticHash": ContentHashSchema
}));

export const RepresentationTokenAccountingSchema: z.ZodType = z.lazy(() => strictObject({
  "sourceTokens": z.number().finite().optional(),
  "outputTokens": z.number().finite().optional(),
  "profileOverheadTokens": z.number().finite().optional(),
  "estimatedNetTokens": z.number().finite().optional(),
  "tokenizerProfileId": z.string().optional()
}));

export const RepresentationProjectionSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "profileId": EntityIdSchema,
  "profileVersion": z.string(),
  "target": RepresentationTargetSchema,
  "sourceEntityIds": z.array(EntityIdSchema),
  "sourceSemanticHash": ContentHashSchema,
  "boundState": StateBindingSchema,
  "contentHash": ContentHashSchema,
  "preservation": SemanticPreservationFingerprintSchema,
  "tokenAccounting": RepresentationTokenAccountingSchema.optional(),
  "status": z.union([z.literal("valid"), z.literal("suspect"), z.literal("invalid"), z.literal("fallback-used")]),
  "validatorResults": z.array(ValidationResultSchema),
  "semanticHash": ContentHashSchema
}));

export const RepresentationProjectionRefSchema: z.ZodType = z.lazy(() => strictObject({
  "projectionId": EntityIdSchema,
  "profileId": EntityIdSchema,
  "profileVersion": z.string(),
  "contentHash": ContentHashSchema,
  "preservationHash": ContentHashSchema
}));

export const StateDigestSchema: z.ZodType = z.lazy(() => strictObject({
  "gitBase": z.string(),
  "worktreeDigest": ContentHashSchema,
  "canonicalProjectorDigest": ContentHashSchema,
  "toolchainDigest": ContentHashSchema,
  "pinnedExternalSnapshotDigest": ContentHashSchema.optional()
}));

export const StateValueDependencyKindSchema: z.ZodType = z.lazy(() => z.union([z.literal("canonical-entity"), z.literal("canonical-governance"), z.literal("projection-unit"), z.literal("artifact"), z.literal("toolchain"), z.literal("adapter"), z.literal("signature-profile"), z.literal("representation-profile"), z.literal("external-snapshot")]));

export const StateValueDependencyRefSchema: z.ZodType = z.lazy(() => strictObject({
  "kind": StateValueDependencyKindSchema,
  "id": z.union([EntityIdSchema, z.string()]),
  "versionHash": ContentHashSchema,
  "role": z.string()
}));

export const StateQueryKindSchema: z.ZodType = z.lazy(() => z.union([z.literal("semantic-identity-search"), z.literal("relation-neighborhood"), z.literal("reverse-derivation"), z.literal("selector-membership"), z.literal("impact-rule-applicability"), z.literal("decision-applicability"), z.literal("implementation-binding"), z.literal("event-topology"), z.literal("contract-topology"), z.literal("verification-binding"), z.literal("package-dependency"), z.literal("surface-enumeration"), z.literal("custom")]));

export const StateQuerySpecSchema: z.ZodType = z.lazy(() => strictObject({
  "id": z.string(),
  "kind": StateQueryKindSchema,
  "programId": z.string(),
  "programVersion": z.string(),
  "input": z.record(z.string(), JsonValueSchema),
  "semanticHash": ContentHashSchema
}));

export const StateQueryResultFingerprintSchema: z.ZodType = z.lazy(() => strictObject({
  "queryHash": ContentHashSchema,
  "resultHash": ContentHashSchema,
  "resultCount": z.number().finite(),
  "observability": ObservabilityClassSchema,
  "assumptions": z.array(z.string()),
  "unavailableLanes": z.array(z.string()),
  "dependencyKeys": z.array(z.string())
}));

export const StateQueryDependencySchema: z.ZodType = z.lazy(() => strictObject({
  "query": StateQuerySpecSchema,
  "priorResult": StateQueryResultFingerprintSchema,
  "role": z.string()
}));

export const StateBindingSchema: z.ZodType = z.lazy(() => strictObject({
  "compiledAgainst": StateDigestSchema,
  "valueDependencies": z.array(StateValueDependencyRefSchema),
  "queryDependencies": z.array(StateQueryDependencySchema),
  "dependencyDigest": ContentHashSchema
}));

export const StateBindingValidationSchema: z.ZodType = z.lazy(() => strictObject({
  "status": z.union([z.literal("current"), z.literal("rebound"), z.literal("stale"), z.literal("suspect"), z.literal("unavailable")]),
  "currentState": StateDigestSchema,
  "changedValueDependencyIds": z.array(z.union([EntityIdSchema, z.string()])),
  "changedQueryDependencyIds": z.array(z.string()),
  "reasons": z.array(z.string()),
  "rebound": StateBindingSchema.optional()
}));

export const ValidationResultSchema: z.ZodType = z.lazy(() => strictObject({
  "validatorId": z.string(),
  "status": z.union([z.literal("passed"), z.literal("failed"), z.literal("skipped"), z.literal("blocked")]),
  "summary": z.string(),
  "evidenceIds": z.array(EntityIdSchema),
  "evidenceLane": z.union([z.literal("compiler"), z.literal("test"), z.literal("schema"), z.literal("runtime"), z.literal("property"), z.literal("representation"), z.literal("architecture"), z.literal("historical"), z.literal("human"), z.literal("independent-agent"), z.literal("same-packet-agent")]),
  "independenceGroup": z.string(),
  "assurance": z.union([z.literal("weak"), z.literal("supporting"), z.literal("strong"), z.literal("exact")]),
  "authorSource": z.string(),
  "sideEffectClass": z.union([z.literal("none"), z.literal("read-only"), z.literal("workspace-write"), z.literal("external-write")]),
  "details": z.record(z.string(), JsonValueSchema),
  "startedAt": z.string(),
  "completedAt": z.string()
}));

export const RollbackSpecSchema: z.ZodType = z.lazy(() => strictObject({
  "kind": z.union([z.literal("git-checkpoint"), z.literal("inverse-transform"), z.literal("compensation"), z.literal("manual"), z.literal("none")]),
  "checkpointId": z.string().optional(),
  "transformId": z.string().optional(),
  "instructions": z.string().optional()
}));

export const OperationEvidenceSchema: z.ZodType = z.lazy(() => strictObject({
  "operationId": z.string(),
  "executor": z.union([z.literal("transform"), z.literal("agent"), z.literal("manual"), z.literal("external")]),
  "unitIds": z.array(EntityIdSchema),
  "beforeHashes": z.array(ContentHashSchema),
  "afterHashes": z.array(ContentHashSchema),
  "evidenceIds": z.array(EntityIdSchema),
  "summary": z.string()
}));

export const AnalyzerCapabilitiesSchema: z.ZodType = z.lazy(() => strictObject({
  "analyzerId": z.string(),
  "adapterVersion": z.string(),
  "supportedLanguages": z.array(z.string()),
  "supportedSemantics": z.array(z.string()),
  "enumeration": EnumerationContractSchema,
  "executesRepositoryCode": z.boolean()
}));

export const AnalyzerFailureSchema: z.ZodType = z.lazy(() => strictObject({
  "analyzerId": z.string(),
  "capability": z.string(),
  "scope": z.string(),
  "message": z.string(),
  "recoverable": z.boolean(),
  "affectedClaimKinds": z.array(z.string())
}));

export const ArtifactFingerprintSchema: z.ZodType = z.lazy(() => strictObject({
  "contentHash": ContentHashSchema,
  "structuralSignature": SemanticSignatureSchema.optional(),
  "semanticSignature": SemanticSignatureSchema.optional(),
  "adapterVersion": z.string()
}));

export const TransformPreviewSchema: z.ZodType = z.lazy(() => strictObject({
  "applicable": z.boolean(),
  "operations": z.array(z.record(z.string(), JsonValueSchema)),
  "touchedUnitIds": z.array(EntityIdSchema),
  "expectedDiff": z.string(),
  "warnings": z.array(z.string())
}));

export const TransformResultSchema: z.ZodType = z.lazy(() => strictObject({
  "transformId": z.string(),
  "changed": z.boolean(),
  "touchedUnitIds": z.array(EntityIdSchema),
  "operations": z.array(OperationEvidenceSchema),
  "checkpointId": z.string().optional()
}));

export const SurfaceChangeSchema: z.ZodType = z.lazy(() => strictObject({
  "semanticChangeId": EntityIdSchema,
  "surfaceId": EntityIdSchema,
  "operation": z.string(),
  "payload": z.record(z.string(), JsonValueSchema)
}));

export const SurfacePlanSchema: z.ZodType = z.lazy(() => strictObject({
  "adapterId": z.string(),
  "surfaceId": EntityIdSchema,
  "riskClass": RiskClassSchema,
  "operations": z.array(z.record(z.string(), JsonValueSchema)),
  "requiredApprovals": z.array(z.string()),
  "validatorIds": z.array(z.string()),
  "boundState": StateBindingSchema
}));

export const SurfaceApplyResultSchema: z.ZodType = z.lazy(() => strictObject({
  "changed": z.boolean(),
  "operationEvidence": z.array(OperationEvidenceSchema),
  "externalReferences": z.array(z.string())
}));

export const RecognizerBindingSchema: z.ZodType = z.lazy(() => strictObject({
  "id": z.string(),
  "version": z.string(),
  "adapterId": z.string(),
  "query": z.record(z.string(), JsonValueSchema),
  "minimumConfidence": ConfidenceSchema
}));

export const ValidatorBindingSchema: z.ZodType = z.lazy(() => strictObject({
  "id": z.string(),
  "version": z.string(),
  "provider": z.string(),
  "input": z.record(z.string(), JsonValueSchema),
  "required": z.boolean(),
  "requiredIndependenceGroup": z.string().optional()
}));

export const TransformBindingSchema: z.ZodType = z.lazy(() => strictObject({
  "id": z.string(),
  "version": z.string(),
  "input": z.record(z.string(), JsonValueSchema),
  "exclusiveUnitClaim": z.boolean()
}));

export const MigrationBindingSchema: z.ZodType = z.lazy(() => strictObject({
  "fromVersion": z.string(),
  "toVersion": z.string(),
  "transformIds": z.array(z.string()),
  "validationIds": z.array(z.string())
}));

export const LensExampleSchema: z.ZodType = z.lazy(() => strictObject({
  "unitId": EntityIdSchema.optional(),
  "artifactLocator": z.string().optional(),
  "explanation": z.string(),
  "evidenceIds": z.array(EntityIdSchema)
}));

export const AuthorityAlternativeSchema: z.ZodType = z.lazy(() => strictObject({
  "key": z.string(),
  "description": z.string(),
  "advantages": z.array(z.string()),
  "disadvantages": z.array(z.string()),
  "rejectedBecause": z.array(z.string()),
  "evidence": z.array(EvidenceRefSchema)
}));

export const ObservabilityClassSchema: z.ZodType = z.lazy(() => z.union([z.literal("closed"), z.literal("bounded"), z.literal("open"), z.literal("sampled"), z.literal("unavailable")]));

export const EnumerationContractSchema: z.ZodType = z.lazy(() => strictObject({
  "observability": ObservabilityClassSchema,
  "method": z.string(),
  "assumptions": z.array(z.string()),
  "blindSpots": z.array(z.string()),
  "dynamicMechanisms": z.array(z.string()),
  "freshnessRequirement": z.string().optional()
}));

export const SurfaceCapabilitiesSchema: z.ZodType = z.lazy(() => strictObject({
  "read": z.boolean(),
  "write": z.boolean(),
  "watch": z.boolean(),
  "transactionalWrites": z.boolean(),
  "stableAnchors": z.boolean(),
  "humanApprovalRequired": z.boolean()
}));

export const SurfaceSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "key": z.string(),
  "kind": z.union([z.literal("repository"), z.literal("ci"), z.literal("cloud"), z.literal("package-registry"), z.literal("app-store"), z.literal("website"), z.literal("runtime"), z.literal("database"), z.literal("external")]),
  "adapter": z.string(),
  "access": z.union([z.literal("read-write"), z.literal("read-only"), z.literal("declared-only"), z.literal("unavailable")]),
  "enumeration": EnumerationContractSchema,
  "capabilities": SurfaceCapabilitiesSchema,
  "boundary": z.record(z.string(), JsonValueSchema)
}));

export const ArtifactSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "surfaceId": EntityIdSchema,
  "locator": z.string(),
  "mediaType": z.string(),
  "contentHash": ContentHashSchema,
  "structuralSignature": SemanticSignatureSchema.optional(),
  "semanticSignature": SemanticSignatureSchema.optional(),
  "observedAt": z.string(),
  "observationRevision": z.string(),
  "causalOrigin": CausalOriginSchema,
  "metadata": z.record(z.string(), JsonValueSchema)
}));

export const SemanticAnchorSchema: z.ZodType = z.lazy(() => strictObject({
  "kind": z.union([z.literal("file"), z.literal("symbol"), z.literal("ast-node"), z.literal("json-pointer"), z.literal("yaml-path"), z.literal("markdown-section"), z.literal("workflow-job"), z.literal("resource-property"), z.literal("external-field")]),
  "value": z.string(),
  "fallbackSignature": SemanticSignatureSchema.optional()
}));

export const ControlPolicySchema: z.ZodType = z.lazy(() => strictObject({
  "ownership": z.union([z.literal("exclusive"), z.literal("structured"), z.literal("shared"), z.literal("observed")]),
  "mutation": z.union([z.literal("replace"), z.literal("transform"), z.literal("agent"), z.literal("external"), z.literal("none")]),
  "actuation": z.union([z.literal("automatic"), z.literal("approval"), z.literal("human"), z.literal("unavailable")])
}));

export const LensRefSchema: z.ZodType = z.lazy(() => strictObject({
  "lensId": EntityIdSchema,
  "version": z.string(),
  "semanticHash": ContentHashSchema
}));

export const ValidityStateSchema: z.ZodType = z.lazy(() => z.union([z.literal("valid"), z.literal("suspect"), z.literal("invalid"), z.literal("revalidating"), z.literal("repair-planned"), z.literal("blocked"), z.literal("unreachable")]));

export const ProjectionUnitSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "artifactId": EntityIdSchema,
  "key": z.string(),
  "role": z.union([z.literal("implementation"), z.literal("contract"), z.literal("test"), z.literal("fixture"), z.literal("documentation"), z.literal("comment"), z.literal("configuration"), z.literal("deployment"), z.literal("publication"), z.literal("telemetry"), z.literal("migration"), z.literal("supporting")]),
  "anchor": SemanticAnchorSchema,
  "control": ControlPolicySchema,
  "conceptIds": z.array(EntityIdSchema),
  "requirementIds": z.array(EntityIdSchema),
  "scenarioIds": z.array(EntityIdSchema),
  "lenses": z.array(LensRefSchema),
  "tags": z.array(z.string()),
  "structuralSignature": SemanticSignatureSchema,
  "semanticSignature": SemanticSignatureSchema,
  "membershipHash": ContentHashSchema,
  "validity": ValidityStateSchema,
  "confidence": ConfidenceSchema,
  "causalOrigin": CausalOriginSchema,
  "generatedFromUnitIds": z.array(EntityIdSchema)
}));

export const EvidenceKindSchema: z.ZodType = z.lazy(() => z.union([z.literal("explicit-decision"), z.literal("repository-structure"), z.literal("code-relationship"), z.literal("test"), z.literal("documentation"), z.literal("git-history"), z.literal("runtime-observation"), z.literal("build-output"), z.literal("official-documentation"), z.literal("standard"), z.literal("research-paper"), z.literal("reference-implementation"), z.literal("issue-or-incident"), z.literal("user-decision"), z.literal("agent-inference")]));

export const EvidenceClaimSchema: z.ZodType = z.lazy(() => strictObject({
  "subjectKey": z.string(),
  "predicate": z.string(),
  "object": JsonValueSchema,
  "inferenceConfidence": ConfidenceSchema.optional()
}));

export const EvidenceSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "kind": EvidenceKindSchema,
  "locator": z.string(),
  "capturedAt": z.string(),
  "sourceDate": z.string().optional(),
  "contentHash": ContentHashSchema,
  "excerpt": z.string().optional(),
  "claims": z.array(EvidenceClaimSchema),
  "reliability": z.union([z.literal("mechanically-proven"), z.literal("high"), z.literal("medium"), z.literal("low"), z.literal("untrusted")]),
  "normativeAuthority": z.union([z.literal("binding-decision"), z.literal("hard-constraint"), z.literal("authoritative-guidance"), z.literal("supporting"), z.literal("descriptive-only"), z.literal("none")]),
  "independenceGroup": z.string(),
  "applicability": z.union([z.literal("direct"), z.literal("analogous"), z.literal("contextual"), z.literal("uncertain")]),
  "freshness": ConfidenceSchema,
  "causalOrigin": CausalOriginSchema,
  "metadata": z.record(z.string(), JsonValueSchema)
}));

export const AuthorityVectorSchema: z.ZodType = z.lazy(() => strictObject({
  "explicitDecisionAlignment": z.number().finite(),
  "productConstraintFit": z.number().finite(),
  "semanticFit": z.number().finite(),
  "independentOccurrence": z.number().finite(),
  "historicalStability": z.number().finite(),
  "independentValidationSupport": z.number().finite(),
  "boundaryCoherence": z.number().finite(),
  "maintenanceOutcome": z.number().finite(),
  "platformCompatibility": z.number().finite(),
  "externalRationale": z.number().finite(),
  "ecosystemHealth": z.number().finite(),
  "securitySupport": z.number().finite(),
  "reversibility": z.number().finite(),
  "migrationCost": z.number().finite(),
  "counterEvidence": z.number().finite()
}));

export const AuthorityReconsiderTriggerSchema: z.ZodType = z.lazy(() => z.union([strictObject({
  "type": z.literal("concept-changed"),
  "conceptId": EntityIdSchema
}), strictObject({
  "type": z.literal("requirement-changed"),
  "subjectId": z.union([EntityIdSchema, z.string()])
}), strictObject({
  "type": z.literal("scenario-changed"),
  "scenarioId": EntityIdSchema
}), strictObject({
  "type": z.literal("relation-changed"),
  "relationId": EntityIdSchema
}), strictObject({
  "type": z.literal("constraint-changed"),
  "constraintId": EntityIdSchema
}), strictObject({
  "type": z.literal("scope-expanded"),
  "scopeKey": z.string()
}), strictObject({
  "type": z.literal("surface-added"),
  "surfaceKind": z.union([z.literal("repository"), z.literal("ci"), z.literal("cloud"), z.literal("package-registry"), z.literal("app-store"), z.literal("website"), z.literal("runtime"), z.literal("database"), z.literal("external")])
}), strictObject({
  "type": z.literal("assumption-falsified"),
  "assumptionKey": z.string()
}), strictObject({
  "type": z.literal("lens-changed"),
  "lensId": EntityIdSchema
}), strictObject({
  "type": z.literal("evidence-invalidated"),
  "evidenceId": EntityIdSchema
}), strictObject({
  "type": z.literal("evidence-refresh-required"),
  "policyKey": z.string()
}), strictObject({
  "type": z.literal("toolchain-version"),
  "tool": z.string(),
  "constraint": z.string()
}), strictObject({
  "type": z.literal("platform-version"),
  "platform": z.string(),
  "constraint": z.string()
}), strictObject({
  "type": z.literal("project-preference-changed"),
  "preferenceId": EntityIdSchema
}), strictObject({
  "type": z.literal("counterevidence-threshold"),
  "subjectId": EntityIdSchema,
  "threshold": z.number().finite()
}), strictObject({
  "type": z.literal("date"),
  "at": z.string()
}), strictObject({
  "type": z.literal("manual-review")
})]));

export const EvidenceRefreshPolicySchema: z.ZodType = z.lazy(() => strictObject({
  "key": z.string(),
  "mode": z.union([z.literal("on-trigger"), z.literal("version-sensitive"), z.literal("max-age"), z.literal("manual")]),
  "maxAgeDays": z.number().finite().optional(),
  "trackedTechnologies": z.array(z.string()).optional(),
  "requireOfficialSourceWhenAvailable": z.boolean()
}));

export const AuthorityRecordSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "key": z.string(),
  "subjectId": EntityIdSchema,
  "status": z.union([z.literal("provisional"), z.literal("approved"), z.literal("auto-approved"), z.literal("rejected"), z.literal("superseded")]),
  "conclusion": z.union([z.literal("preserve"), z.literal("normalize"), z.literal("migrate"), z.literal("exception"), z.literal("unknown")]),
  "rationale": z.string(),
  "alternatives": z.array(AuthorityAlternativeSchema),
  "assumptions": z.array(z.string()),
  "reconsiderWhen": z.array(AuthorityReconsiderTriggerSchema),
  "evidenceRefreshPolicy": EvidenceRefreshPolicySchema.optional(),
  "vector": AuthorityVectorSchema,
  "assessmentConfidence": z.union([z.literal("low"), z.literal("medium"), z.literal("high")]),
  "evidence": z.array(EvidenceRefSchema),
  "governanceRiskClass": RiskClassSchema,
  "decidedBy": z.union([z.literal("system"), z.literal("user"), z.literal("policy")]),
  "createdAt": z.string(),
  "semanticHash": ContentHashSchema
}));

export const SemanticIdentityCandidateSchema: z.ZodType = z.lazy(() => strictObject({
  "entityId": EntityIdSchema,
  "entityKind": z.union([z.literal("concept"), z.literal("requirement"), z.literal("scenario")]),
  "similarity": ConfidenceSchema,
  "ownershipFit": ConfidenceSchema,
  "boundaryFit": ConfidenceSchema,
  "evidence": z.array(EvidenceRefSchema),
  "explanation": z.string()
}));

export const NewSemanticBoundarySchema: z.ZodType = z.lazy(() => strictObject({
  "owns": z.array(z.string()),
  "excludes": z.array(z.string()),
  "nearestEntityIds": z.array(EntityIdSchema),
  "rationale": z.string()
}));

export const SemanticIdentityResolutionSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "requestedMeaning": z.string(),
  "requestedKind": z.union([z.literal("concept"), z.literal("requirement"), z.literal("scenario"), z.literal("unknown")]),
  "outcome": z.union([z.literal("reuse-existing"), z.literal("coordinated-modification"), z.literal("split-existing"), z.literal("merge-existing"), z.literal("replace-existing"), z.literal("create-new"), z.literal("no-durable-entity"), z.literal("unresolved")]),
  "candidates": z.array(SemanticIdentityCandidateSchema),
  "selectedEntityIds": z.array(EntityIdSchema),
  "newBoundary": NewSemanticBoundarySchema.optional(),
  "confidence": ConfidenceSchema,
  "evidence": z.array(EvidenceRefSchema),
  "unknowns": z.array(z.string()),
  "boundState": StateBindingSchema,
  "contentHash": ContentHashSchema
}));

export const RelevanceBandSchema: z.ZodType = z.lazy(() => z.union([z.literal("direct"), z.literal("governing"), z.literal("consequence"), z.literal("possible")]));

export const RelevanceSeedSchema: z.ZodType = z.lazy(() => strictObject({
  "kind": z.union([z.literal("request-term"), z.literal("semantic-entity"), z.literal("projection-unit"), z.literal("artifact"), z.literal("code-symbol"), z.literal("contract"), z.literal("event"), z.literal("decision"), z.literal("manual")]),
  "subjectId": z.union([EntityIdSchema, z.string()]).optional(),
  "value": z.string().optional(),
  "reason": z.string(),
  "confidence": ConfidenceSchema
}));

export const RelevanceReasonSchema: z.ZodType = z.lazy(() => strictObject({
  "kind": z.union([z.literal("explicit"), z.literal("identity-match"), z.literal("governs"), z.literal("constrains"), z.literal("depends-on"), z.literal("implementation-binding"), z.literal("selector-applicability"), z.literal("event-producer-consumer"), z.literal("contract-producer-consumer"), z.literal("verification-binding"), z.literal("package-dependency"), z.literal("historical-cochange"), z.literal("semantic-similarity"), z.literal("model-inference"), z.literal("analysis-facet"), z.literal("open-world-widening")]),
  "fromId": z.union([EntityIdSchema, z.string()]).optional(),
  "weight": z.number().finite(),
  "provenance": z.union([z.literal("declared"), z.literal("derived"), z.literal("observed"), z.literal("inferred")]),
  "confidence": ConfidenceSchema,
  "explanation": z.string(),
  "evidenceIds": z.array(EntityIdSchema)
}));

export const RelevanceEntrySchema: z.ZodType = z.lazy(() => strictObject({
  "entityId": EntityIdSchema,
  "band": RelevanceBandSchema,
  "score": z.number().finite(),
  "requiredForPlanning": z.boolean(),
  "reasons": z.array(RelevanceReasonSchema)
}));

export const RelevanceClosureSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "requestHash": ContentHashSchema,
  "seeds": z.array(RelevanceSeedSchema),
  "entries": z.array(RelevanceEntrySchema),
  "activatedFacetKeys": z.array(z.string()),
  "unknowns": z.array(z.string()),
  "unavailableLanes": z.array(z.string()),
  "boundState": StateBindingSchema,
  "contentHash": ContentHashSchema
}));

export const AnalysisFacetSchema: z.ZodType = z.lazy(() => strictObject({
  "key": z.string(),
  "version": z.string(),
  "selector": SelectorExprSchema,
  "questionKeys": z.array(z.string()),
  "relevanceRuleIds": z.array(z.string()),
  "requiredEvidenceLanes": z.array(z.union([z.literal("compiler"), z.literal("test"), z.literal("schema"), z.literal("runtime"), z.literal("property"), z.literal("representation"), z.literal("architecture"), z.literal("historical"), z.literal("human"), z.literal("independent-agent"), z.literal("same-packet-agent")])),
  "outputKinds": z.array(z.string())
}));

export const PlanningSurpriseSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "planId": EntityIdSchema,
  "kind": z.union([z.literal("unpredicted-semantic-impact"), z.literal("unpredicted-code-impact"), z.literal("missing-relation"), z.literal("scope-expansion"), z.literal("agent-overreach"), z.literal("benign-discovery")]),
  "predictedEntityIds": z.array(EntityIdSchema),
  "observedEntityIds": z.array(EntityIdSchema),
  "unexpectedEntityIds": z.array(EntityIdSchema),
  "evidence": z.array(EvidenceRefSchema),
  "explanation": z.string(),
  "disposition": z.union([z.literal("accept-and-learn"), z.literal("accept-no-model-change"), z.literal("repair-plan"), z.literal("revert-overreach"), z.literal("human-decision"), z.literal("unresolved")]),
  "proposedRelationIds": z.array(EntityIdSchema),
  "contentHash": ContentHashSchema
}));

export const RiskClassSchema: z.ZodType = z.lazy(() => z.union([z.literal("R0"), z.literal("R1"), z.literal("R2"), z.literal("R3"), z.literal("R4")]));

export const RiskAssessmentSchema: z.ZodType = z.lazy(() => strictObject({
  "class": RiskClassSchema,
  "inherentOperationRisk": z.number().finite(),
  "affectedUnitCount": z.number().finite(),
  "affectedSurfaceCount": z.number().finite(),
  "publicContractImpact": z.boolean(),
  "externalImpact": z.boolean(),
  "dataImpact": z.boolean(),
  "reversibility": z.union([z.literal("full"), z.literal("strong"), z.literal("partial"), z.literal("none")]),
  "validationStrength": z.union([z.literal("weak"), z.literal("supporting"), z.literal("strong"), z.literal("exact")]),
  "closureConfidence": z.union([z.literal("proven"), z.literal("bounded"), z.literal("high"), z.literal("partial"), z.literal("unknown")]),
  "unresolvedIdentityCount": z.number().finite(),
  "relevanceFrontierCount": z.number().finite(),
  "openWorldDependencies": z.boolean(),
  "unresolvedBlockingConcernCount": z.number().finite(),
  "suspectDecisionCount": z.number().finite(),
  "compensationAvailable": z.boolean(),
  "reasons": z.array(z.string())
}));

export const ExecutionPolicySchema: z.ZodType = z.lazy(() => strictObject({
  "preset": z.union([z.literal("observe"), z.literal("guide"), z.literal("govern"), z.literal("autonomous"), z.literal("salvage")]),
  "maximumAutomaticRisk": RiskClassSchema,
  "network": z.union([z.literal("deny"), z.literal("ask"), z.literal("allow")]),
  "externalWrites": z.union([z.literal("deny"), z.literal("approval"), z.literal("allow-with-capability")]),
  "requireIndependentValidationAtOrAbove": RiskClassSchema,
  "requireWorktreeAtOrAbove": RiskClassSchema,
  "allowAutoPromotion": z.boolean(),
  "allowAutoMutation": z.boolean(),
  "maxChangedUnits": z.number().finite().optional(),
  "maxChangedSurfaces": z.number().finite().optional(),
  "maxCost": z.number().finite().optional(),
  "maxTokens": z.number().finite().optional()
}));

export const PatternCandidateSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "key": z.string(),
  "purposeHypothesis": z.string(),
  "memberUnitIds": z.array(EntityIdSchema),
  "excludedUnitIds": z.array(EntityIdSchema),
  "counterExamples": z.array(EntityIdSchema),
  "independenceGroups": z.array(z.string()),
  "alternatives": z.array(z.string()),
  "confidence": ConfidenceSchema,
  "evidence": z.array(EvidenceRefSchema),
  "semanticHash": ContentHashSchema
}));

export const LensContributionRoleSchema: z.ZodType = z.lazy(() => z.union([z.literal("projection-owner"), z.literal("constraint-contributor"), z.literal("validator-contributor"), z.literal("migration-overlay")]));

export const ProjectionExpectationSchema: z.ZodType = z.lazy(() => z.union([strictObject({
  "kind": z.literal("exact-output"),
  "generatorId": z.string(),
  "expectedSignatureProfile": z.string()
}), strictObject({
  "kind": z.literal("structured-template"),
  "structureValidatorId": z.string(),
  "authoredHoles": z.array(z.string())
}), strictObject({
  "kind": z.literal("predicate-constrained"),
  "predicateIds": z.array(z.string()),
  "validatorIds": z.array(z.string())
}), strictObject({
  "kind": z.literal("observed-state"),
  "comparisonPolicyId": z.string()
}), strictObject({
  "kind": z.literal("human-procedure"),
  "procedureId": z.string(),
  "evidenceRequirements": z.array(z.string())
})]));

export const ProjectionSpecSchema: z.ZodType = z.lazy(() => strictObject({
  "role": z.union([z.literal("implementation"), z.literal("contract"), z.literal("test"), z.literal("fixture"), z.literal("documentation"), z.literal("comment"), z.literal("configuration"), z.literal("deployment"), z.literal("publication"), z.literal("telemetry"), z.literal("migration"), z.literal("supporting")]),
  "cardinality": z.union([z.literal("one"), z.literal("zero-or-one"), z.literal("many"), z.literal("at-least-one")]),
  "surfaceKind": z.union([z.literal("repository"), z.literal("ci"), z.literal("cloud"), z.literal("package-registry"), z.literal("app-store"), z.literal("website"), z.literal("runtime"), z.literal("database"), z.literal("external")]),
  "selector": SelectorExprSchema,
  "control": ControlPolicySchema,
  "expectation": ProjectionExpectationSchema
}));

export const ProjectionLensSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "key": z.string(),
  "version": z.string(),
  "status": z.union([z.literal("candidate"), z.literal("shadow"), z.literal("active"), z.literal("deprecated"), z.literal("retired")]),
  "purpose": z.string(),
  "realizesConceptKinds": z.array(z.union([z.literal("capability"), z.literal("behavior"), z.literal("invariant"), z.literal("decision"), z.literal("ownership"), z.literal("obligation"), z.literal("data"), z.literal("interface"), z.literal("event"), z.literal("command"), z.literal("policy"), z.literal("read-model"), z.literal("contract"), z.literal("assumption"), z.literal("migration"), z.literal("constraint")])),
  "selector": SelectorExprSchema,
  "contributions": z.array(LensContributionRoleSchema),
  "expectedProjections": z.array(ProjectionSpecSchema),
  "rules": z.array(RuleSchema),
  "impactRules": z.array(ImpactRuleSchema),
  "recognizers": z.array(RecognizerBindingSchema),
  "validators": z.array(ValidatorBindingSchema),
  "transforms": z.array(TransformBindingSchema),
  "migrations": z.array(MigrationBindingSchema),
  "conflictsWith": z.array(LensRefSchema),
  "compatibleWith": z.array(LensRefSchema),
  "examples": z.array(LensExampleSchema),
  "counterExamples": z.array(LensExampleSchema),
  "authorityRecordId": EntityIdSchema,
  "governanceBasis": z.array(GovernanceBasisSchema),
  "semanticHash": ContentHashSchema
}));

export const SelectorExprSchema: z.ZodType = z.lazy(() => z.union([strictObject({
  "op": z.literal("all"),
  "items": z.array(SelectorExprSchema)
}), strictObject({
  "op": z.literal("any"),
  "items": z.array(SelectorExprSchema)
}), strictObject({
  "op": z.literal("not"),
  "item": SelectorExprSchema
}), strictObject({
  "op": z.literal("atom"),
  "field": z.union([z.literal("path"), z.literal("language"), z.literal("artifact-role"), z.literal("concept"), z.literal("concept-kind"), z.literal("requirement"), z.literal("scenario"), z.literal("lens"), z.literal("surface"), z.literal("package"), z.literal("package-kind"), z.literal("operation"), z.literal("platform"), z.literal("migration-phase"), z.literal("risk"), z.literal("tag"), z.literal("control-ownership"), z.literal("control-mutation"), z.literal("ast-pattern"), z.literal("relation"), z.literal("causal-origin")]),
  "matcher": z.union([z.literal("equals"), z.literal("in"), z.literal("glob"), z.literal("regex"), z.literal("contains"), z.literal("exists"), z.literal("matches-structural-query")]),
  "value": JsonValueSchema
})]));

export const IgnorePolicySchema: z.ZodType = z.lazy(() => strictObject({
  "inventory": z.array(SelectorExprSchema),
  "inferenceAuthority": z.array(SelectorExprSchema),
  "mutation": z.array(SelectorExprSchema),
  "reporting": z.array(SelectorExprSchema),
  "modelContext": z.array(SelectorExprSchema),
  "coverageDenominator": z.array(SelectorExprSchema)
}));

export const RuleEffectSchema: z.ZodType = z.lazy(() => z.union([z.literal("require"), z.literal("forbid"), z.literal("prefer"), z.literal("validate"), z.literal("transform"), z.literal("route"), z.literal("grant"), z.literal("restrict"), z.literal("explain")]));

export const AuthorityClassSchema: z.ZodType = z.lazy(() => z.union([z.literal("host-safety"), z.literal("platform-constraint"), z.literal("approved-user-intent"), z.literal("active-lens"), z.literal("adopted-external-standard"), z.literal("migration-overlay"), z.literal("local-convention"), z.literal("inferred-candidate"), z.literal("task-suggestion")]));

export const NormalizedPredicateSchema: z.ZodType = z.lazy(() => z.union([strictObject({
  "kind": z.literal("path-under"),
  "root": z.string()
}), strictObject({
  "kind": z.literal("path-not-under"),
  "root": z.string()
}), strictObject({
  "kind": z.literal("relation-required"),
  "relation": RelationTypeSchema,
  "targetSelector": SelectorExprSchema
}), strictObject({
  "kind": z.literal("relation-forbidden"),
  "relation": RelationTypeSchema,
  "targetSelector": SelectorExprSchema
}), strictObject({
  "kind": z.literal("cardinality"),
  "selector": SelectorExprSchema,
  "min": z.number().finite().optional(),
  "max": z.number().finite().optional()
}), strictObject({
  "kind": z.literal("dependency-allowed"),
  "from": SelectorExprSchema,
  "to": SelectorExprSchema
}), strictObject({
  "kind": z.literal("dependency-forbidden"),
  "from": SelectorExprSchema,
  "to": SelectorExprSchema
}), strictObject({
  "kind": z.literal("permission"),
  "operation": z.string(),
  "allowed": z.boolean()
}), strictObject({
  "kind": z.literal("unit-state"),
  "state": ValidityStateSchema
}), strictObject({
  "kind": z.literal("schema-valid"),
  "schemaId": z.string()
}), strictObject({
  "kind": z.literal("validator"),
  "validatorId": z.string()
})]));

export const RuleSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "key": z.string(),
  "version": z.string(),
  "effect": RuleEffectSchema,
  "authorityClass": AuthorityClassSchema,
  "governanceBasis": z.array(GovernanceBasisSchema),
  "selector": SelectorExprSchema,
  "predicates": z.array(NormalizedPredicateSchema),
  "advisoryPayload": z.record(z.string(), JsonValueSchema).optional(),
  "rationale": z.string(),
  "evidence": z.array(EvidenceRefSchema),
  "conflictPolicy": z.union([z.literal("error"), z.literal("merge"), z.literal("higher-authority"), z.literal("explicit-exception-only")]),
  "validatorIds": z.array(z.string()),
  "transformIds": z.array(z.string()),
  "semanticHash": ContentHashSchema
}));

export const RuleConflictSchema: z.ZodType = z.lazy(() => strictObject({
  "ruleIds": z.array(EntityIdSchema),
  "unitId": EntityIdSchema,
  "kind": z.union([z.literal("require-forbid"), z.literal("exclusive-transform"), z.literal("authority-override"), z.literal("ambiguous-selector"), z.literal("incompatible-predicate")]),
  "explanation": z.string(),
  "evidenceIds": z.array(EntityIdSchema)
}));

export const EffectiveRuleBundleSchema: z.ZodType = z.lazy(() => strictObject({
  "unitId": EntityIdSchema,
  "operation": z.string(),
  "rules": z.array(RuleSchema),
  "suppressedRules": z.array(strictObject({
  "ruleId": EntityIdSchema,
  "reason": z.string(),
  "supersededBy": EntityIdSchema.optional()
})),
  "predicates": z.array(NormalizedPredicateSchema),
  "conflicts": z.array(RuleConflictSchema),
  "dependencyFingerprint": ContentHashSchema,
  "bundleHash": ContentHashSchema
}));

export const DerivationInputSchema: z.ZodType = z.lazy(() => strictObject({
  "kind": z.union([z.literal("concept"), z.literal("requirement"), z.literal("scenario"), z.literal("relation"), z.literal("lens"), z.literal("rule-bundle"), z.literal("unit"), z.literal("artifact"), z.literal("external-constraint"), z.literal("toolchain"), z.literal("adapter"), z.literal("signature-profile"), z.literal("representation-profile"), z.literal("representation-projection")]),
  "id": z.union([EntityIdSchema, z.string()]),
  "versionHash": ContentHashSchema,
  "role": z.string()
}));

export const DerivationRecordSchema: z.ZodType = z.lazy(() => strictObject({
  "unitId": EntityIdSchema,
  "proofGroupId": EntityIdSchema.optional(),
  "engineVersion": z.string(),
  "adapterVersion": z.string(),
  "inputs": z.array(DerivationInputSchema),
  "ruleBundleHash": ContentHashSchema,
  "outputSemanticSignature": SemanticSignatureSchema,
  "outputStructuralSignature": SemanticSignatureSchema,
  "membershipHash": ContentHashSchema,
  "establishedAt": z.string(),
  "validators": z.array(ValidationResultSchema)
}));

export const ImpactRuleSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "key": z.string(),
  "version": z.string(),
  "selector": SelectorExprSchema,
  "trigger": z.union([z.literal("concept-change"), z.literal("interface-change"), z.literal("membership-change"), z.literal("removal"), z.literal("lens-change"), z.literal("rule-change"), z.literal("decision-change"), z.literal("concern-resolution"), z.literal("representation-profile-change"), z.literal("external-change"), z.literal("manual")]),
  "direction": z.union([z.literal("forward"), z.literal("reverse"), z.literal("both")]),
  "relationTypes": z.array(RelationTypeSchema).optional(),
  "maxDepth": z.number().finite().optional(),
  "effect": z.union([z.literal("invalidate"), z.literal("revalidate"), z.literal("widen-analysis"), z.literal("advisory"), z.literal("block")]),
  "requiredRelationConfidence": z.number().finite().optional(),
  "semanticHash": ContentHashSchema
}));

export const InvalidationCauseSchema: z.ZodType = z.lazy(() => strictObject({
  "eventKind": z.string(),
  "subjectId": z.union([EntityIdSchema, z.string()]),
  "oldHash": ContentHashSchema.optional(),
  "newHash": ContentHashSchema.optional()
}));

export const InvalidationEventSchema: z.ZodType = z.lazy(() => strictObject({
  "eventKind": z.string(),
  "subjectId": z.union([EntityIdSchema, z.string()]),
  "oldHash": ContentHashSchema.optional(),
  "newHash": ContentHashSchema.optional(),
  "graphRevision": z.number().finite(),
  "stateDigest": StateDigestSchema
}));

export const InvalidationResultSchema: z.ZodType = z.lazy(() => strictObject({
  "directlyAffected": z.array(EntityIdSchema),
  "transitivelyAffected": z.array(EntityIdSchema),
  "possibleFrontier": z.array(EntityIdSchema),
  "unavailable": z.array(EntityIdSchema),
  "reasons": z.record(EntityIdSchema, z.array(z.string()))
}));

export const RepairStrategySchema: z.ZodType = z.lazy(() => z.union([z.literal("reuse"), z.literal("revalidate"), z.literal("deterministic-patch"), z.literal("regenerate"), z.literal("agent-repair"), z.literal("widen-analysis"), z.literal("human-decision")]));

export const RepairCapabilitiesSchema: z.ZodType = z.lazy(() => strictObject({
  "validatorCanProveValidity": z.boolean(),
  "deterministicPatch": z.boolean(),
  "patchIsReversible": z.boolean(),
  "generator": z.boolean(),
  "upstreamSourceKnown": z.boolean()
}));

export const ContextPrecedentSchema: z.ZodType = z.lazy(() => strictObject({
  "unitId": EntityIdSchema,
  "similarity": ConfidenceSchema,
  "relevance": z.string(),
  "evidenceIds": z.array(EntityIdSchema)
}));

export const ScopeGrantSchema: z.ZodType = z.lazy(() => strictObject({
  "selector": SelectorExprSchema,
  "operations": z.array(z.string()),
  "reason": z.string()
}));

export const CompletionContractSchema: z.ZodType = z.lazy(() => strictObject({
  "requiredUnitStates": z.array(strictObject({
  "unitId": EntityIdSchema,
  "state": z.union([z.literal("valid"), z.literal("removed"), z.literal("exception")])
})),
  "requiredValidators": z.array(z.string()),
  "requiredEvidenceLanes": z.array(z.union([z.literal("compiler"), z.literal("test"), z.literal("schema"), z.literal("runtime"), z.literal("property"), z.literal("representation"), z.literal("architecture"), z.literal("historical"), z.literal("human"), z.literal("independent-agent"), z.literal("same-packet-agent")])),
  "minimumValidationAssurance": z.union([z.literal("weak"), z.literal("supporting"), z.literal("strong"), z.literal("exact")]),
  "requireIndependentValidation": z.boolean(),
  "maximumNewDivergences": z.number().finite(),
  "maximumUnknowns": z.number().finite(),
  "allowUnavailableExternalActions": z.boolean(),
  "requiredArtifacts": z.array(z.string()),
  "cleanWorkingTree": z.boolean()
}));

export const ExecutionCapsuleSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "taskId": EntityIdSchema,
  "objective": z.string(),
  "operation": z.string(),
  "unitIds": z.array(EntityIdSchema),
  "boundState": StateBindingSchema,
  "relevanceClosureId": EntityIdSchema,
  "analysisFacetKeys": z.array(z.string()),
  "requirementIds": z.array(EntityIdSchema),
  "scenarioIds": z.array(EntityIdSchema),
  "conceptSummary": z.string(),
  "decisionIds": z.array(EntityIdSchema),
  "decisionSummary": z.string(),
  "unresolvedArchitectureConcerns": z.array(EntityIdSchema),
  "lensSummary": z.string(),
  "effectiveRules": z.array(EffectiveRuleBundleSchema),
  "normativeKernelHash": ContentHashSchema,
  "representation": RepresentationProjectionRefSchema.optional(),
  "relevantPrecedents": z.array(ContextPrecedentSchema),
  "allowedWrites": z.array(ScopeGrantSchema),
  "forbiddenWrites": z.array(ScopeGrantSchema),
  "availablePrimitives": z.array(z.string()),
  "requiredValidations": z.array(z.string()),
  "upstreamImplications": z.array(z.string()),
  "downstreamImplications": z.array(z.string()),
  "knownExceptions": z.array(z.string()),
  "unknowns": z.array(z.string()),
  "risk": RiskAssessmentSchema,
  "completionContract": CompletionContractSchema,
  "contextDependencyHash": ContentHashSchema,
  "contextHash": ContentHashSchema
}));

export const CommandSpecSchema: z.ZodType = z.lazy(() => strictObject({
  "id": z.string(),
  "argv": z.array(z.string()),
  "cwd": z.string(),
  "readScope": z.array(z.string()),
  "writeScope": z.array(z.string()),
  "network": z.union([z.literal("deny"), z.literal("allow")]),
  "environmentKeys": z.array(z.string()),
  "sideEffectClass": z.union([z.literal("none"), z.literal("read-only"), z.literal("workspace-write"), z.literal("external-write")]),
  "timeoutMs": z.number().finite(),
  "cpuBudgetMs": z.number().finite().optional(),
  "memoryBudgetMb": z.number().finite().optional()
}));

export const CoverageLaneSchema: z.ZodType = z.lazy(() => strictObject({
  "key": z.string(),
  "observability": ObservabilityClassSchema,
  "numerator": z.number().finite(),
  "denominator": z.number().finite().optional(),
  "confidence": ConfidenceSchema,
  "assumptions": z.array(z.string()),
  "blindSpots": z.array(z.string()),
  "analyzerFailures": z.array(AnalyzerFailureSchema),
  "staleObservationIds": z.array(z.string()),
  "exactClosureProvable": z.boolean()
}));

export const CoverageSnapshotSchema: z.ZodType = z.lazy(() => strictObject({
  "graphRevision": z.number().finite(),
  "boundary": z.array(z.string()),
  "lanes": z.array(CoverageLaneSchema),
  "completeWithinBoundary": z.boolean(),
  "allowsBoundedAgentRepair": z.boolean(),
  "unknownFrontierIds": z.array(EntityIdSchema),
  "unavailableSurfaceIds": z.array(EntityIdSchema),
  "proofStatement": z.union([z.literal("proven-within-boundary"), z.literal("bounded"), z.literal("high-confidence"), z.literal("partial"), z.literal("not-established")])
}));

export const DivergenceSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "type": z.string(),
  "title": z.string(),
  "severity": z.union([z.literal("info"), z.literal("low"), z.literal("medium"), z.literal("high"), z.literal("critical")]),
  "confidence": ConfidenceSchema,
  "leverage": z.number().finite(),
  "status": z.union([z.literal("open"), z.literal("auto-fixed"), z.literal("planned"), z.literal("accepted-exception"), z.literal("dismissed"), z.literal("blocked")]),
  "expected": z.record(z.string(), JsonValueSchema),
  "observed": z.record(z.string(), JsonValueSchema),
  "conceptIds": z.array(EntityIdSchema),
  "requirementIds": z.array(EntityIdSchema),
  "scenarioIds": z.array(EntityIdSchema),
  "unitIds": z.array(EntityIdSchema),
  "ruleIds": z.array(EntityIdSchema),
  "evidence": z.array(EvidenceRefSchema),
  "counterEvidence": z.array(EvidenceRefSchema),
  "rationale": z.string(),
  "possibleIntentionality": z.array(z.string()),
  "recommendedDisposition": z.string(),
  "repairStrategies": z.array(RepairStrategySchema),
  "coverageCaveat": z.string(),
  "semanticHash": ContentHashSchema
}));

export const PlanCheckpointSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "afterPacketIds": z.array(EntityIdSchema),
  "requiredValidators": z.array(z.string()),
  "rollback": RollbackSpecSchema
}));

export const ExecutionPlanSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "revision": z.number().finite(),
  "supersedesPlanId": EntityIdSchema.optional(),
  "semanticChangeId": EntityIdSchema.optional(),
  "sourceRunId": EntityIdSchema,
  "boundState": StateBindingSchema,
  "relevanceClosureId": EntityIdSchema.optional(),
  "predictedImpactClosureHash": ContentHashSchema.optional(),
  "boundary": z.array(z.string()),
  "assumptions": z.array(z.string()),
  "knownAffectedUnitIds": z.array(EntityIdSchema),
  "possibleFrontierUnitIds": z.array(EntityIdSchema),
  "unavailableSurfaceIds": z.array(EntityIdSchema),
  "packetIds": z.array(EntityIdSchema),
  "checkpoints": z.array(PlanCheckpointSchema),
  "completionCriteria": CompletionContractSchema,
  "recommendedNextChunk": z.string().optional()
}));

export const IntentStatementSchema: z.ZodType = z.lazy(() => strictObject({
  "kind": z.union([z.literal("behavior"), z.literal("constraint"), z.literal("non-goal"), z.literal("assumption"), z.literal("implementation-proposal")]),
  "statement": z.string(),
  "origin": z.array(IntentOriginRefSchema),
  "confidence": ConfidenceSchema
}));

export const ChangeIntentAnalysisSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "request": z.string(),
  "normalizedIntent": z.string(),
  "statements": z.array(IntentStatementSchema),
  "ambiguity": z.array(z.string()),
  "assumptions": z.array(z.string()),
  "contentHash": ContentHashSchema
}));

export const RequirementDeltaSchema: z.ZodType = z.lazy(() => strictObject({
  "subjectType": z.literal("requirement"),
  "kind": z.union([z.literal("add"), z.literal("modify"), z.literal("remove"), z.literal("supersede")]),
  "requirementId": EntityIdSchema.optional(),
  "proposedRequirement": RequirementSchema.optional(),
  "rationale": z.string()
}).superRefine((value, context) => {
  const needsExistingId = value.kind !== "add";
  const needsProposedValue = value.kind !== "remove";
  if (needsExistingId !== (value.requirementId !== undefined)) context.addIssue({ code: "custom", path: ["requirementId"], message: needsExistingId ? "existing ID is required" : "add cannot name an existing ID" });
  if (needsProposedValue !== (value.proposedRequirement !== undefined)) context.addIssue({ code: "custom", path: ["proposedRequirement"], message: needsProposedValue ? "proposed value is required" : "remove cannot carry a proposed value" });
}));

export const BehavioralScenarioDeltaSchema: z.ZodType = z.lazy(() => strictObject({
  "subjectType": z.literal("scenario"),
  "kind": z.union([z.literal("add"), z.literal("modify"), z.literal("remove"), z.literal("supersede")]),
  "scenarioId": EntityIdSchema.optional(),
  "proposedScenario": BehavioralScenarioSchema.optional(),
  "rationale": z.string()
}).superRefine((value, context) => {
  const needsExistingId = value.kind !== "add";
  const needsProposedValue = value.kind !== "remove";
  if (needsExistingId !== (value.scenarioId !== undefined)) context.addIssue({ code: "custom", path: ["scenarioId"], message: needsExistingId ? "existing ID is required" : "add cannot name an existing ID" });
  if (needsProposedValue !== (value.proposedScenario !== undefined)) context.addIssue({ code: "custom", path: ["proposedScenario"], message: needsProposedValue ? "proposed value is required" : "remove cannot carry a proposed value" });
}));

export const SemanticOperationSchema: z.ZodType = z.lazy(() => strictObject({
  "kind": z.union([z.literal("add"), z.literal("modify"), z.literal("remove"), z.literal("replace"), z.literal("migrate"), z.literal("adopt-rule"), z.literal("deprecate-rule"), z.literal("resolve-divergence")]),
  "subjectType": z.union([z.literal("concept"), z.literal("relation"), z.literal("decision"), z.literal("lens"), z.literal("rule"), z.literal("projection"), z.literal("surface"), z.literal("other")]),
  "subjectKey": z.string(),
  "subjectId": EntityIdSchema.optional(),
  "payload": z.record(z.string(), JsonValueSchema)
}));

export const ChangeOperationSchema: z.ZodType = z.lazy(() => z.union([SemanticOperationSchema, RequirementDeltaSchema, BehavioralScenarioDeltaSchema]));

export const ImpactClosureRefSchema: z.ZodType = z.lazy(() => strictObject({
  "contentHash": ContentHashSchema,
  "knownAffectedUnitIds": z.array(EntityIdSchema),
  "possibleFrontierUnitIds": z.array(EntityIdSchema),
  "unavailableSurfaceIds": z.array(EntityIdSchema)
}));

export const SemanticChangeSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "request": z.string(),
  "normalizedIntent": z.string(),
  "intentAnalysisId": EntityIdSchema,
  "identityResolutionIds": z.array(EntityIdSchema),
  "relevanceClosureId": EntityIdSchema,
  "analysisFacetKeys": z.array(z.string()),
  "operations": z.array(ChangeOperationSchema),
  "decisionIds": z.array(EntityIdSchema),
  "assumptions": z.array(z.string()),
  "boundary": z.array(z.string()),
  "predictedImpact": ImpactClosureRefSchema.optional(),
  "risk": RiskAssessmentSchema,
  "status": z.union([z.literal("draft"), z.literal("analyzed"), z.literal("approved"), z.literal("executing"), z.literal("complete"), z.literal("blocked")])
}));

export const WorkPacketSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "planId": EntityIdSchema,
  "title": z.string(),
  "strategy": RepairStrategySchema,
  "unitIds": z.array(EntityIdSchema),
  "dependencies": z.array(EntityIdSchema),
  "capsuleId": EntityIdSchema,
  "risk": RiskAssessmentSchema,
  "executionMode": z.union([z.literal("deterministic"), z.literal("agent"), z.literal("manual"), z.literal("external")]),
  "transformId": z.string().optional(),
  "validatorIds": z.array(z.string()),
  "rollback": RollbackSpecSchema,
  "boundState": StateBindingSchema,
  "status": z.union([z.literal("pending"), z.literal("running"), z.literal("succeeded"), z.literal("failed"), z.literal("blocked"), z.literal("skipped")])
}));

export const TransactionPhaseSchema: z.ZodType = z.lazy(() => z.union([z.literal("prepared"), z.literal("workspace-mutating"), z.literal("workspace-staged"), z.literal("validating"), z.literal("canonical-staging"), z.literal("committing"), z.literal("committed"), z.literal("rolling-back"), z.literal("rolled-back"), z.literal("recovery-required")]));

export const TransactionJournalEntrySchema: z.ZodType = z.lazy(() => strictObject({
  "transactionId": EntityIdSchema,
  "planId": EntityIdSchema,
  "phase": TransactionPhaseSchema,
  "beforeState": StateDigestSchema,
  "intendedAfterCanonicalDigest": ContentHashSchema.optional(),
  "worktreePath": z.string(),
  "checkpointIds": z.array(z.string()),
  "touchedPaths": z.array(z.string()),
  "externalOperationIds": z.array(z.string()),
  "updatedAt": z.string()
}));

export const TransactionReceiptSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "planId": EntityIdSchema,
  "semanticChangeId": EntityIdSchema.optional(),
  "riskClass": RiskClassSchema,
  "beforeState": StateDigestSchema,
  "afterState": StateDigestSchema,
  "changedCanonicalEntityIds": z.array(EntityIdSchema),
  "changedRequirementIds": z.array(EntityIdSchema),
  "changedScenarioIds": z.array(EntityIdSchema),
  "changedUnitIds": z.array(EntityIdSchema),
  "validationSummaryHash": ContentHashSchema,
  "certificateHash": ContentHashSchema.optional(),
  "rollbackRef": z.string().optional(),
  "createdAt": z.string(),
  "semanticHash": ContentHashSchema
}));

export const ChangeCertificateSchema: z.ZodType = z.lazy(() => strictObject({
  "id": EntityIdSchema,
  "planId": EntityIdSchema,
  "baseGitRevision": z.string().optional(),
  "resultingGitRevision": z.string().optional(),
  "semanticChange": SemanticChangeSchema.optional(),
  "relevanceClosureHash": ContentHashSchema.optional(),
  "predictedImpactClosureHash": ContentHashSchema.optional(),
  "observedImpactClosureHash": ContentHashSchema.optional(),
  "beforeState": StateDigestSchema,
  "afterState": StateDigestSchema.optional(),
  "changedConcepts": z.array(EntityIdSchema),
  "changedRequirements": z.array(EntityIdSchema),
  "changedScenarios": z.array(EntityIdSchema),
  "changedRelations": z.array(EntityIdSchema),
  "changedUnits": z.array(EntityIdSchema),
  "planningSurpriseIds": z.array(EntityIdSchema),
  "deterministicOperations": z.array(OperationEvidenceSchema),
  "agentOperations": z.array(OperationEvidenceSchema),
  "validations": z.array(ValidationResultSchema),
  "divergencesResolved": z.array(EntityIdSchema),
  "divergencesIntroduced": z.array(EntityIdSchema),
  "modeledBoundary": z.array(z.string()),
  "completeness": z.union([z.literal("proven-within-boundary"), z.literal("bounded"), z.literal("high-confidence"), z.literal("partial"), z.literal("not-established")]),
  "unknowns": z.array(z.string()),
  "unavailableActions": z.array(z.string()),
  "rollback": z.array(RollbackSpecSchema),
  "createdAt": z.string()
}));

export const StructuredModelRequestSchema: z.ZodType = z.lazy(() => strictObject({
  "purpose": z.string(),
  "role": z.union([z.literal("classify"), z.literal("infer-concepts"), z.literal("resolve-identity"), z.literal("discover-relevance"), z.literal("analyze-intent"), z.literal("infer-pattern"), z.literal("research-synthesis"), z.literal("architecture"), z.literal("bounded-edit"), z.literal("representation-render"), z.literal("representation-review"), z.literal("adversarial-review"), z.literal("judge")]),
  "programVersion": z.string(),
  "schemaName": z.string(),
  "schemaVersion": z.string(),
  "schema": JsonValueSchema,
  "input": z.record(z.string(), JsonValueSchema),
  "inputHash": ContentHashSchema,
  "executionCapsule": ExecutionCapsuleSchema.optional(),
  "risk": RiskAssessmentSchema,
  "maxInputTokens": z.number().finite().optional(),
  "maxOutputTokens": z.number().finite().optional(),
  "maxCost": z.number().finite().optional()
}));

export const StructuredModelResponseSchema: z.ZodType = z.lazy(() => strictObject({
  "value": JsonValueSchema,
  "provider": z.string(),
  "model": z.string(),
  "providerRevision": z.string().optional(),
  "inputTokens": z.number().finite().optional(),
  "outputTokens": z.number().finite().optional(),
  "rawResponseHash": ContentHashSchema,
  "attempt": z.number().finite()
}));
