import { hashFramedDomain, type ChangeIntentAnalysis, type ContentHash, type RiskAssessment, type StateDigest } from "@projector/core";
import { describe, expect, it, vi } from "vitest";

import { createStateBinding } from "../state/index.js";
import { compileSemanticChange, type AuthenticatedChangeCompilerFacts } from "./compiler.js";

const state: StateDigest = { gitBase: "base", worktreeDigest: hashFramedDomain("t16", "w"), canonicalProjectorDigest: hashFramedDomain("t16", "c"), toolchainDigest: hashFramedDomain("t16", "t") };
const binding = createStateBinding({ compiledAgainst: state, valueDependencies: [{ kind: "canonical-entity", id: "requirement:checkout", versionHash: hashFramedDomain("t16", "r"), role: "change subject" }], queryDependencies: [] });
const risk: RiskAssessment = { class: "R1", inherentOperationRisk: 1, affectedUnitCount: 1, affectedSurfaceCount: 1, publicContractImpact: false, externalImpact: false, dataImpact: false, reversibility: "full", validationStrength: "strong", closureConfidence: "bounded", unresolvedIdentityCount: 0, relevanceFrontierCount: 0, openWorldDependencies: false, unresolvedBlockingConcernCount: 0, suspectDecisionCount: 0, compensationAvailable: true, reasons: [] };
const intent = (): ChangeIntentAnalysis => {
  const base = { id: "intent:checkout", request: "Make checkout retry safely; Redis is only a proposal", normalizedIntent: "checkout retries safely", statements: [{ kind: "behavior" as const, statement: "checkout retries safely", origin: [], confidence: 1 }, { kind: "implementation-proposal" as const, statement: "Redis", origin: [], confidence: 1 }], ambiguity: [], assumptions: [] };
  return { ...base, contentHash: hashFramedDomain("change-intent-analysis", base) };
};
function facts(patch: Partial<AuthenticatedChangeCompilerFacts["value"]> = {}): AuthenticatedChangeCompilerFacts {
  const value = { intentAnalysis: intent(), identityResolutionIds: ["identity:checkout"], relevanceClosureId: "closure:checkout", analysisFacetKeys: ["behavior"], operations: [{ provenance: "authenticated" as const, operation: { subjectType: "requirement" as const, kind: "modify" as const, requirementId: "requirement:checkout", rationale: "retry behavior" } }, { provenance: "inferred" as const, operation: { subjectType: "other" as const, subjectKey: "redis", kind: "replace" as const, payload: { technology: "Redis" } } }], relations: [], assumptions: [], boundary: ["packages/api"], boundState: binding, ...patch };
  return { value, contentHash: hashFramedDomain("authenticated-change-compiler-facts", value) };
}
const context = { repositoryRoot: "/repo", stateDigest: state, config: {}, signal: new AbortController().signal };

describe("authenticated semantic change compiler", () => {
  it("keeps implementation proposals candidate-only, calls architecture before impact, and derives stable identity/risk", async () => {
    const order: string[] = [];
    const compiled = await compileSemanticChange({ request: intent().request, currentState: state, context }, { facts: { load: async () => facts() }, bindingValidator: { validate: async () => ({ status: "current" as const, currentState: state, changedValueDependencyIds: [], changedQueryDependencyIds: [], reasons: [] }) }, authority: { verify: async () => true }, architecture: { preflight: async () => { order.push("architecture"); return { allowed: true, decisionIds: [], contentHash: hashFramedDomain("change-architecture-preflight", { allowed: true, decisionIds: [] }) }; } }, impact: { compile: async () => { order.push("impact"); const value = { knownAffectedUnitIds: ["unit:checkout"], possibleFrontierUnitIds: [], unavailableSurfaceIds: [], reasons: [{ unitId: "unit:checkout", kind: "exact" as const, reason: "reverse dependency" }], queryDependencyIds: ["query:reverse"] }; return { value, contentHash: hashFramedDomain("authenticated-impact-closure", value) }; } }, risk: { assess: async () => ({ value: risk, contentHash: hashFramedDomain("authenticated-change-risk", risk) }) } });
    expect(order).toEqual(["architecture", "impact"]);
    expect(compiled.change.operations).toHaveLength(1); expect(compiled.candidateOperations).toHaveLength(1);
    expect(compiled.change.analysisFacetKeys).toEqual(["behavior"]); expect(compiled.change.risk).toEqual(risk);
    const reordered = await compileSemanticChange({ request: "different wording", currentState: state, context }, { facts: { load: async () => facts({ operations: [...facts().value.operations].reverse() }) }, bindingValidator: { validate: async () => ({ status: "current" as const, currentState: state, changedValueDependencyIds: [], changedQueryDependencyIds: [], reasons: [] }) }, authority: { verify: async () => true }, architecture: { preflight: async () => ({ allowed: true, decisionIds: [], contentHash: hashFramedDomain("change-architecture-preflight", { allowed: true, decisionIds: [] }) }) }, impact: { compile: async () => { const value = { knownAffectedUnitIds: ["unit:checkout"], possibleFrontierUnitIds: [], unavailableSurfaceIds: [], reasons: [{ unitId: "unit:checkout", kind: "exact" as const, reason: "reverse dependency" }], queryDependencyIds: ["query:reverse"] }; return { value, contentHash: hashFramedDomain("authenticated-impact-closure", value) }; } }, risk: { assess: async () => ({ value: risk, contentHash: hashFramedDomain("authenticated-change-risk", risk) }) } });
    expect(reordered.change.id).toBe(compiled.change.id);
  });

  it("fails closed on forged facts, ambiguity, operation conflicts, dangling relations, authority, and downgraded risk", async () => {
    const basePorts = { bindingValidator: { validate: async () => ({ status: "current" as const, currentState: state, changedValueDependencyIds: [], changedQueryDependencyIds: [], reasons: [] }) }, authority: { verify: vi.fn(async () => true) }, architecture: { preflight: async () => ({ allowed: true, decisionIds: [], contentHash: hashFramedDomain("change-architecture-preflight", { allowed: true, decisionIds: [] }) }) }, impact: { compile: async () => { const value = { knownAffectedUnitIds: [], possibleFrontierUnitIds: [], unavailableSurfaceIds: [], reasons: [], queryDependencyIds: [] }; return { value, contentHash: hashFramedDomain("authenticated-impact-closure", value) }; } }, risk: { assess: async () => ({ value: risk, contentHash: hashFramedDomain("authenticated-change-risk", risk) }) } };
    await expect(compileSemanticChange({ request: "x", currentState: state, context }, { ...basePorts, facts: { load: async () => ({ ...facts(), contentHash: hashFramedDomain("t16", "forged") as ContentHash }) } })).rejects.toThrow(/facts|hash|authenticated/iu);
    await expect(compileSemanticChange({ request: "x", currentState: state, context }, { ...basePorts, facts: { load: async () => facts({ identityResolutionIds: [] }) } })).rejects.toThrow(/identity|ambig/iu);
    const conflicting = [...facts().value.operations, { provenance: "authenticated" as const, operation: { subjectType: "requirement" as const, kind: "remove" as const, requirementId: "requirement:checkout", rationale: "conflict" } }];
    await expect(compileSemanticChange({ request: "x", currentState: state, context }, { ...basePorts, facts: { load: async () => facts({ operations: conflicting }) } })).rejects.toThrow(/conflict/iu);
    await expect(compileSemanticChange({ request: "x", currentState: state, context }, { ...basePorts, facts: { load: async () => facts({ operations: [{ provenance: "authenticated", operation: { subjectType: "requirement", kind: "remove", requirementId: "requirement:checkout", rationale: "remove" } }], relations: [{ id: "relation:req-scenario", subjectIds: ["requirement:checkout", "scenario:retry"] }] }) } })).rejects.toThrow(/relation|dangling/iu);
    await expect(compileSemanticChange({ request: "x", currentState: state, context }, { ...basePorts, authority: { verify: async () => false }, facts: { load: async () => facts() } })).rejects.toThrow(/authority/iu);
    await expect(compileSemanticChange({ request: "x", currentState: state, context }, { ...basePorts, facts: { load: async () => facts() }, risk: { assess: async () => ({ value: { ...risk, class: "R0" }, contentHash: hashFramedDomain("authenticated-change-risk", { ...risk, class: "R0" }) }) } })).rejects.toThrow(/risk|downgrad/iu);
  });
});
