import { appendFile, mkdir, readFile, rm } from "node:fs/promises";
import { posix } from "node:path";
import { canonicalJson, hashFramedDomain, type ContentHash } from "@projector/core";
import { RepositoryPathService } from "../security/repository-path.js";

export type ReportFormat = "text" | "json" | "md" | "sarif";
export interface OperationalFinding { readonly id: ContentHash; readonly code: string; readonly title: string; readonly path?: string; readonly severity: "note" | "warning" | "error"; readonly evidenceIds: readonly string[] }
type FindingInput = Omit<OperationalFinding, "id">;
export interface OperationalExitProof { readonly commandFailed: boolean; readonly blockingInvalidity: boolean; readonly approvalRequired: boolean; readonly incompleteCoverage: boolean; readonly requiredUnavailable: boolean; readonly recoveryFailure: boolean; readonly budgetExhausted: boolean; readonly resumable: boolean }
export type OperationalEvidenceValue = ContentHash | { readonly unavailable: string };
export interface OperationalRunEvidence {
  readonly configDigest: OperationalEvidenceValue; readonly toolchainDigest: OperationalEvidenceValue; readonly gitHead: OperationalEvidenceValue; readonly worktreeDigest: OperationalEvidenceValue; readonly canonicalDigest: OperationalEvidenceValue;
  readonly graphRecords: readonly string[]; readonly analyzerRecords: readonly string[]; readonly modelRecords: readonly string[]; readonly snapshotRecords: readonly string[]; readonly decisionRecords: readonly string[]; readonly transformRecords: readonly string[]; readonly validationRecords: readonly string[]; readonly journalRecords: readonly string[]; readonly errorRecords: readonly string[]; readonly durationMs: number | { readonly unavailable: string };
}
export interface OperationalReport { readonly version: 1; readonly runId: string; readonly command: string; readonly exitCode: number; readonly exitProof: OperationalExitProof; readonly evidence: OperationalRunEvidence; readonly policy: unknown; readonly stateDigest: ContentHash; readonly unavailableFields: readonly string[]; readonly findings: readonly OperationalFinding[]; readonly dtoHash: ContentHash }
export interface OperationalReportInput { readonly runId: string; readonly command: string; readonly exitProof: OperationalExitProof; readonly evidence: OperationalRunEvidence; readonly policy: unknown; readonly stateDigest: ContentHash; readonly unavailableFields: readonly string[]; readonly findings: readonly FindingInput[] }

export function unavailableOperationalEvidence(reason: string): OperationalRunEvidence { const unavailable = { unavailable: reason }; return { configDigest: unavailable, toolchainDigest: unavailable, gitHead: unavailable, worktreeDigest: unavailable, canonicalDigest: unavailable, graphRecords: [], analyzerRecords: [], modelRecords: [], snapshotRecords: [], decisionRecords: [], transformRecords: [], validationRecords: [], journalRecords: [], errorRecords: [], durationMs: unavailable }; }
export function deriveOperationalExitCode(proof: OperationalExitProof): number { return proof.budgetExhausted && proof.resumable ? 7 : proof.recoveryFailure ? 6 : proof.requiredUnavailable ? 5 : proof.incompleteCoverage ? 4 : proof.approvalRequired ? 3 : proof.blockingInvalidity ? 2 : proof.commandFailed || proof.budgetExhausted ? 1 : 0; }

const secretKey = /(?:authorization|credential|password|private[_-]?key|api[_-]?key|access[_-]?token|secret)/iu;
const classify = (value: string, key?: string): "private-key" | "credential" | "token" | undefined => /-----BEGIN [A-Z ]*PRIVATE KEY-----/u.test(value) ? "private-key" : /(?:authorization\s*:|password\s*=|credential)/iu.test(value) || (key !== undefined && secretKey.test(key)) ? "credential" : /(?:gh[pousr]_[A-Za-z0-9]{20,}|bearer\s+[A-Za-z0-9._~+\/-]{8,}|[A-Za-z0-9_-]{32,}\.[A-Za-z0-9_-]{8,})/iu.test(value) ? "token" : undefined;
export function redactBeforeBoundary(value: unknown, key?: string): unknown {
  if (typeof value === "string") { const kind = classify(value, key); return kind === undefined ? value : `<redacted:${kind}>`; }
  if (Array.isArray(value)) return value.map((item) => redactBeforeBoundary(item));
  if (value !== null && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([name, item]) => [name, redactBeforeBoundary(item, name)]));
  return value;
}
function body(report: OperationalReport | Omit<OperationalReport, "dtoHash">): Omit<OperationalReport, "dtoHash"> { const { dtoHash: omitted, ...value } = report as OperationalReport; void omitted; return value; }
export function createOperationalReport(input: OperationalReportInput): OperationalReport {
  const findings = input.findings.map((finding) => ({ ...finding, evidenceIds: [...new Set(finding.evidenceIds)].sort(), id: hashFramedDomain("operational-finding", finding) })).sort((left, right) => left.id.localeCompare(right.id));
  const hasUnclassifiedError = findings.some(({ severity }) => severity === "error") && !input.exitProof.commandFailed && !input.exitProof.blockingInvalidity && !input.exitProof.approvalRequired && !input.exitProof.incompleteCoverage && !input.exitProof.requiredUnavailable && !input.exitProof.recoveryFailure && !input.exitProof.budgetExhausted;
  const exitProof = { ...input.exitProof, blockingInvalidity: input.exitProof.blockingInvalidity || hasUnclassifiedError };
  const base = redactBeforeBoundary({ version: 1 as const, runId: input.runId, command: input.command, exitCode: deriveOperationalExitCode(exitProof), exitProof, evidence: input.evidence, policy: input.policy, stateDigest: input.stateDigest, unavailableFields: [...new Set(input.unavailableFields)].sort(), findings }) as Omit<OperationalReport, "dtoHash">;
  return { ...base, dtoHash: hashFramedDomain("operational-report-dto", base) };
}
export function validateOperationalReport(report: OperationalReport): boolean { return report.dtoHash === hashFramedDomain("operational-report-dto", body(report)) && report.exitCode === deriveOperationalExitCode(report.exitProof) && (report.exitCode !== 0 || report.findings.every(({ severity }) => severity !== "error")); }
export function renderOperationalReport(report: OperationalReport, format: ReportFormat): string {
  if (!validateOperationalReport(report)) throw new Error("operational report authentication failed");
  if (format === "json") return JSON.stringify(report, null, 2);
  if (format === "sarif") return JSON.stringify({ version: "2.1.0", runs: [{ tool: { driver: { name: "Projector" } }, results: report.findings.map((finding) => ({ ruleId: finding.code, level: finding.severity, message: { text: finding.title }, fingerprints: { projectorFindingId: finding.id }, properties: { evidenceIds: finding.evidenceIds }, locations: finding.path === undefined ? [] : [{ physicalLocation: { artifactLocation: { uri: finding.path } } }] })) }] }, null, 2);
  const lines = report.findings.map((finding) => `${finding.severity.toUpperCase()} ${finding.code}: ${finding.title}${finding.path === undefined ? "" : ` (${finding.path})`}`);
  return format === "md" ? [`# Projector ${report.command}`, "", ...report.findings.map((finding) => `- **${finding.severity} ${finding.code}**: ${finding.title}${finding.path === undefined ? "" : ` (\`${finding.path}\`)`}`)].join("\n") : [`Projector ${report.command} (exit ${report.exitCode})`, ...lines].join("\n");
}
interface TelemetryLine { readonly version: 1; readonly sequence: number; readonly previousHash: ContentHash | null; readonly report: OperationalReport; readonly entryHash: ContentHash }
const delay = (milliseconds: number) => new Promise<void>((resolve) => setTimeout(resolve, milliseconds));
export class JsonlTelemetryStore {
  private constructor(private readonly paths: RepositoryPathService, private readonly path: string, private readonly maximumRecords: number) {}
  static async create(paths: RepositoryPathService, path: string, maximumRecords = 10_000): Promise<JsonlTelemetryStore> { if (!Number.isSafeInteger(maximumRecords) || maximumRecords < 1) throw new Error("telemetry bound must be positive"); const parent = posix.dirname(paths.canonicalize(path)); const resolved = await paths.resolveWrite(parent); await mkdir(resolved.realTarget, { recursive: true }); await paths.resolveWrite(path); return new JsonlTelemetryStore(paths, path, maximumRecords); }
  private async acquire(): Promise<() => Promise<void>> { const lockPath = `${this.path}.lock`; for (let attempt = 0; attempt < 200; attempt += 1) { const lock = await this.paths.resolveWrite(lockPath); try { await mkdir(lock.realTarget); return async () => { const current = await this.paths.resolveWrite(lockPath); await rm(current.realTarget, { recursive: true, force: true }); }; } catch (error) { if (!(error instanceof Error && "code" in error && error.code === "EEXIST")) throw error; await delay(5); } } throw new Error("telemetry append lock budget exhausted"); }
  async append(report: OperationalReport): Promise<TelemetryLine> { const release = await this.acquire(); try { const prior = await this.replay(); const sequence = prior.length + 1; const previousHash = prior.at(-1)?.entryHash ?? null; const safe = createOperationalReport({ ...report, findings: report.findings.map(({ id: omitted, ...finding }) => { void omitted; return finding; }) }); const base = { version: 1 as const, sequence, previousHash, report: safe }; const line = { ...base, entryHash: hashFramedDomain("operational-telemetry-line", base) }; const target = await this.paths.resolveWrite(this.path); await appendFile(target.realTarget, `${canonicalJson(line)}\n`, "utf8"); return line; } finally { await release(); } }
  async replay(): Promise<TelemetryLine[]> { const target = await this.paths.resolveRead(this.path); let text: string; try { text = await readFile(target.realTarget, "utf8"); } catch (error) { if (error instanceof Error && "code" in error && error.code === "ENOENT") return []; throw error; } const lines = text.split(/\r?\n/u).filter(Boolean); if (lines.length > this.maximumRecords) throw new Error(`telemetry JSONL exceeds bounded replay limit ${this.maximumRecords}`); const records: TelemetryLine[] = []; for (const [index, line] of lines.entries()) { let record: TelemetryLine; try { record = JSON.parse(line) as TelemetryLine; } catch { throw new Error(`corrupt telemetry JSONL at sequence ${index + 1}`); } const { entryHash, ...base } = record; if (record.version !== 1 || record.sequence !== index + 1 || record.previousHash !== (records.at(-1)?.entryHash ?? null) || entryHash !== hashFramedDomain("operational-telemetry-line", base) || !validateOperationalReport(record.report)) throw new Error(`corrupt telemetry JSONL hash/sequence at ${index + 1}`); records.push(record); } return records; }
}
