import { hashFramedDomain, type ContentHash } from "@projector/core";

export type AcceptanceStratum = "scenario" | "property" | "adversary";
export interface AcceptanceInventoryItem { readonly id: string; readonly stratum: AcceptanceStratum; readonly ordinal: number; readonly title: string; readonly sourcePath: string; readonly sourceDigest: ContentHash }
export interface AcceptanceSource { readonly path: string; readonly text: string }
export interface TraceabilityEntry extends AcceptanceInventoryItem { readonly publicFacade: string; readonly testRef: string; readonly observation: { readonly id: string; readonly status: "passed" | "failed" | "skipped"; readonly contentHash: ContentHash } }
export interface TraceabilityManifest { readonly version: 1; readonly entries: readonly TraceabilityEntry[]; readonly inventoryHash: ContentHash }

const slug = (value: string) => value.normalize("NFKD").toLowerCase().replace(/[^a-z0-9]+/gu, "-").replace(/^-|-$/gu, "");
const sourceDigest = (path: string, text: string) => hashFramedDomain("acceptance-authoritative-source", { path, text });
function inventoryItem(stratum: AcceptanceStratum, ordinal: number, title: string, source: AcceptanceSource): AcceptanceInventoryItem { return { id: `${stratum}:${String(ordinal).padStart(2, "0")}:${slug(title)}`, stratum, ordinal, title, sourcePath: source.path, sourceDigest: sourceDigest(source.path, source.text) }; }
export function deriveAcceptanceInventory(input: { readonly scenarios: readonly AcceptanceSource[]; readonly testing: AcceptanceSource }): readonly AcceptanceInventoryItem[] {
  let scenarioOrdinal = 0; const scenarios = input.scenarios.flatMap((source) => [...source.text.matchAll(/^## (.+)$/gmu)].map((match) => match[1]!).filter((title) => !/^Relevance and Semantic Identity Acceptance Scenarios$/u.test(title)).map((title) => inventoryItem("scenario", ++scenarioOrdinal, title, source)));
  const propertySection = /## Property-based tests\s+Mandatory properties include:\s+([\s\S]*?)\n## /u.exec(input.testing.text)?.[1]; if (propertySection === undefined) throw new Error("authoritative property inventory is missing"); const properties = [...propertySection.matchAll(/^- (.+)$/gmu)].map((match) => match[1]!).map((title, index) => inventoryItem("property", index + 1, title, input.testing));
  const adversarySection = /## Anti-self-deception tests\s+Mandatory adversarial classes:\s+([\s\S]*?)\n## /u.exec(input.testing.text)?.[1]; if (adversarySection === undefined) throw new Error("authoritative adversary inventory is missing"); const adversaries = [...adversarySection.matchAll(/^\d+\. (.+)$/gmu)].map((match) => match[1]!).map((title, index) => inventoryItem("adversary", index + 1, title, input.testing));
  if (scenarios.length !== 59 || properties.length !== 27 || adversaries.length !== 32) throw new Error(`authoritative acceptance inventory mismatch: ${scenarios.length}/59 scenarios, ${properties.length}/27 properties, ${adversaries.length}/32 adversaries`); return Object.freeze([...scenarios, ...properties, ...adversaries]);
}
const inventoryBody = (entries: readonly Pick<AcceptanceInventoryItem, "id" | "stratum" | "ordinal" | "title" | "sourcePath" | "sourceDigest">[]) => entries.map(({ id, stratum, ordinal, title, sourcePath, sourceDigest }) => ({ id, stratum, ordinal, title, sourcePath, sourceDigest }));
export function traceabilityInventoryHash(inventory: readonly AcceptanceInventoryItem[]): ContentHash { return hashFramedDomain("release-traceability-inventory", inventoryBody(inventory)); }
export function validateTraceabilityManifest(manifest: TraceabilityManifest, inventory: readonly AcceptanceInventoryItem[]): void {
  if (manifest.version !== 1 || manifest.inventoryHash !== traceabilityInventoryHash(inventory)) throw new Error("traceability inventory hash is stale"); if (manifest.entries.length !== inventory.length) throw new Error("traceability entry count is incomplete"); const expected = new Map(inventory.map((item) => [item.id, item])); const seen = new Set<string>();
  for (const entry of manifest.entries) { const item = expected.get(entry.id); if (item === undefined || seen.has(entry.id)) throw new Error(`duplicate, relabeled, or unknown traceability identity ${entry.id}`); seen.add(entry.id); if (entry.stratum !== item.stratum || entry.ordinal !== item.ordinal || entry.title !== item.title || entry.sourcePath !== item.sourcePath || entry.sourceDigest !== item.sourceDigest) throw new Error(`stale traceability mapping ${entry.id}`); if (entry.publicFacade.length === 0 || !entry.testRef.includes("#") || entry.observation.id.length === 0 || entry.observation.status !== "passed" || entry.observation.contentHash !== hashFramedDomain("acceptance-observation", { id: entry.observation.id, status: entry.observation.status, publicFacade: entry.publicFacade, testRef: entry.testRef })) throw new Error(`missing, skipped, or unauthenticated acceptance observation ${entry.id}`); }
}

export interface IndependentConformanceObservation { readonly cleanDigest: ContentHash; readonly incrementalDigest: ContentHash; readonly rawObservationDigest: ContentHash; readonly evidenceIds: readonly string[] }
export function evaluateIndependentConformance(observation: IndependentConformanceObservation): { readonly passed: boolean; readonly reasons: readonly string[]; readonly contentHash: ContentHash } { const reasons = [...(observation.cleanDigest === observation.incrementalDigest ? [] : ["clean and incremental observations differ"]), ...(observation.cleanDigest === observation.rawObservationDigest ? [] : ["shared derived observation contradicts independent raw observation"]), ...(observation.evidenceIds.length > 0 ? [] : ["independent raw evidence is missing"])]; return { passed: reasons.length === 0, reasons, contentHash: hashFramedDomain("independent-release-conformance", observation) }; }

export interface ReleaseDeviation { readonly id: string; readonly severity: "note" | "minor" | "major"; readonly impact: string; readonly evidenceIds: readonly string[]; readonly waivedGateIds: readonly string[] }
export interface ReleaseArtifact { readonly id: string; readonly bytesHash: ContentHash }
export interface ReleaseEvidenceInput { readonly sourceRevision: string; readonly worktreeDigest: ContentHash; readonly toolchainDigest: ContentHash; readonly buildDigest: ContentHash; readonly tarballDigest: ContentHash; readonly rawArtifacts: readonly ReleaseArtifact[]; readonly traceability: TraceabilityManifest; readonly inventory: readonly AcceptanceInventoryItem[]; readonly benchmarkPassed: boolean; readonly rebuildDigest: ContentHash; readonly conformance: ReturnType<typeof evaluateIndependentConformance>; readonly deviations: readonly ReleaseDeviation[] }
export interface ReleaseEvidence extends Omit<ReleaseEvidenceInput, "inventory"> { readonly version: 1; readonly releaseAllowed: true; readonly contentHash: ContentHash }
export function compileReleaseEvidence(input: ReleaseEvidenceInput): ReleaseEvidence { validateTraceabilityManifest(input.traceability, input.inventory); if (input.sourceRevision.length === 0 || input.rawArtifacts.length === 0 || new Set(input.rawArtifacts.map(({ id }) => id)).size !== input.rawArtifacts.length || input.rawArtifacts.some(({ bytesHash }) => !bytesHash.startsWith("sha256:v1:"))) throw new Error("release artifact evidence is incomplete"); if (!input.benchmarkPassed || !input.conformance.passed) throw new Error("release gates cannot be waived"); if (input.deviations.some(({ impact, evidenceIds, waivedGateIds }) => impact.length === 0 || evidenceIds.length === 0 || waivedGateIds.length > 0)) throw new Error("release deviations cannot waive gates or omit evidence"); const { inventory: omitted, ...body } = input; void omitted; const base = { version: 1 as const, releaseAllowed: true as const, ...body }; return Object.freeze({ ...base, contentHash: hashFramedDomain("projector-release-evidence", base) }); }
