import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { hashFramedDomain } from "@projector/core";
import { compileReleaseEvidence, deriveAcceptanceInventory, evaluateIndependentConformance, traceabilityEntryHash, traceabilityInventoryHash, verifyTraceabilityManifest, type AcceptanceSource, type TraceabilityManifest } from "./release-acceptance.js";

const scenarioPaths = ["PROJECTOR_SPEC/12-delivery/acceptance-core.md", "PROJECTOR_SPEC/12-delivery/acceptance-relevance-and-identity.md", "PROJECTOR_SPEC/12-delivery/acceptance-representation.md", "PROJECTOR_SPEC/12-delivery/acceptance-architecture.md"];
async function sources() { const scenarios: AcceptanceSource[] = await Promise.all(scenarioPaths.map(async (path) => ({ path, text: await readFile(path, "utf8") }))); const path = "PROJECTOR_SPEC/11-validation/testing-and-adversarial-evaluation.md"; return { scenarios, testing: { path, text: await readFile(path, "utf8") } }; }
const manifestFor = (inventory: Awaited<ReturnType<typeof deriveAcceptanceInventory>>, testSourceDigest: ReturnType<typeof hashFramedDomain>, testRef = "tests/public.test.ts#supported public behavior"): TraceabilityManifest => ({ version: 2, inventoryHash: traceabilityInventoryHash(inventory), entries: inventory.map((item) => { const entry = { ...item, publicFacade: "projector/testkit", testRef, testSourceDigest }; return { ...entry, mappingHash: traceabilityEntryHash(entry) }; }) });
const rehash = (entry: TraceabilityManifest["entries"][number], changes: Partial<TraceabilityManifest["entries"][number]>) => { const { mappingHash: omitted, ...body } = entry; void omitted; const changed = { ...body, ...changes }; return { ...changed, mappingHash: traceabilityEntryHash(changed) }; };

describe("public release acceptance authority", () => {
  it("derives 59/27/32 heading identities and rejects nonexistent, relabeled, duplicate, or self-rehashed mappings", async () => { const root = await mkdtemp(join(tmpdir(), "traceability-")); try { const inventory = deriveAcceptanceInventory(await sources()); expect(inventory.filter(({ stratum }) => stratum === "scenario")).toHaveLength(59); expect(inventory.filter(({ stratum }) => stratum === "property")).toHaveLength(27); expect(inventory.filter(({ stratum }) => stratum === "adversary")).toHaveLength(32); await mkdir(join(root, "tests")); const testSource = 'import { describe, it } from "vitest"; describe("supported public behavior", () => { it("passes", () => {}); });\n'; await writeFile(join(root, "tests/public.test.ts"), testSource); const sourceHash = hashFramedDomain("traceability-test-source", { path: "tests/public.test.ts", text: testSource }); const manifest = manifestFor(inventory, sourceHash); const run = { passedTestFiles: ["tests/public.test.ts"], rawEvidenceHash: hashFramedDomain("test-run", "passed"), publicFacades: ["projector/testkit"] }; await expect(verifyTraceabilityManifest(manifest, inventory, { repositoryRoot: root, run })).resolves.toMatchObject({ verified: true }); await expect(verifyTraceabilityManifest({ ...manifest, entries: manifest.entries.map((entry, index) => index === 0 ? rehash(entry, { testRef: "does/not/exist.test.ts#fabricated" }) : entry) }, inventory, { repositoryRoot: root, run })).rejects.toThrow(/exist|test/iu); await expect(verifyTraceabilityManifest({ ...manifest, entries: manifest.entries.map((entry, index) => index === 0 ? rehash(entry, { title: "relabeled" }) : entry) }, inventory, { repositoryRoot: root, run })).rejects.toThrow(/stale|relabeled/iu); await expect(verifyTraceabilityManifest({ ...manifest, entries: [...manifest.entries.slice(0, -1), manifest.entries[0]!] }, inventory, { repositoryRoot: root, run })).rejects.toThrow(/duplicate|relabeled/iu); } finally { await rm(root, { recursive: true, force: true }); } });
  it("compares independent clean/incremental derived observations to raw canonical identities and enforces locality", () => { const digest = hashFramedDomain("derived", "same"); const wrong = evaluateIndependentConformance({ clean: { derivedDigest: digest, entityIds: ["entity:wrong"] }, incremental: { derivedDigest: digest, entityIds: ["entity:wrong"] }, rawEntityIds: ["entity:right"], locality: { changedEntityIds: ["entity:right"], recomputedEntityIds: ["entity:right"] }, evidenceIds: ["raw:schema"] }); expect(wrong).toMatchObject({ passed: false, reasons: [expect.stringMatching(/raw/iu)] }); expect(evaluateIndependentConformance({ clean: { derivedDigest: digest, entityIds: ["entity:right"] }, incremental: { derivedDigest: digest, entityIds: ["entity:right"] }, rawEntityIds: ["entity:right"], locality: { changedEntityIds: ["entity:right"], recomputedEntityIds: ["entity:right", "entity:unrelated"] }, evidenceIds: ["raw:schema"] }).passed).toBe(false); });
  it("binds verified traceability and full benchmark results while refusing gate-waiving deviations", async () => { const inventory = deriveAcceptanceInventory(await sources()); const digest = hashFramedDomain("release", "fixture"); const traceability = manifestFor(inventory, digest); const traceabilityVerification = { verified: true as const, inventoryHash: traceability.inventoryHash, runEvidenceHash: digest, contentHash: hashFramedDomain("verified-traceability", { inventoryHash: traceability.inventoryHash, runEvidenceHash: digest, entries: traceability.entries.map(({ mappingHash }) => mappingHash) }) }; const conformance = evaluateIndependentConformance({ clean: { derivedDigest: digest, entityIds: ["entity:a"] }, incremental: { derivedDigest: digest, entityIds: ["entity:a"] }, rawEntityIds: ["entity:a"], locality: { changedEntityIds: ["entity:a"], recomputedEntityIds: ["entity:a"] }, evidenceIds: ["raw:fixture"] }); const benchmark = { metrics: [{ id: "fixture", passed: true }], failures: [], releaseAllowed: true }; const input = { sourceRevision: "revision:fixture", worktreeDigest: digest, toolchainDigest: digest, buildDigest: digest, tarballDigest: digest, rawArtifacts: [{ id: "tarball", bytesHash: digest }], traceability, traceabilityVerification, inventory, benchmark, rebuildDigest: digest, conformance, deviations: [{ id: "deviation:none", severity: "note" as const, impact: "No release-impacting deviation", evidenceIds: ["gate:fixture"], waivedGateIds: [] }] }; expect(compileReleaseEvidence(input)).toMatchObject({ releaseAllowed: true, benchmark, contentHash: expect.stringMatching(/^sha256:v1:/u) }); expect(() => compileReleaseEvidence({ ...input, deviations: [{ ...input.deviations[0]!, waivedGateIds: ["benchmark"] }] })).toThrow(/cannot waive/iu); });
});
