import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { hashFramedDomain } from "@projector/core";
import { compileReleaseEvidence, deriveAcceptanceInventory, evaluateIndependentConformance, traceabilityEntryHash, traceabilityInventoryHash, verifyTraceabilityManifest, type AcceptanceSource, type TraceabilityManifest } from "./release-acceptance.js";

const scenarioPaths = ["PROJECTOR_SPEC/12-delivery/acceptance-core.md", "PROJECTOR_SPEC/12-delivery/acceptance-relevance-and-identity.md", "PROJECTOR_SPEC/12-delivery/acceptance-representation.md", "PROJECTOR_SPEC/12-delivery/acceptance-architecture.md"];
async function sources() { const scenarios: AcceptanceSource[] = await Promise.all(scenarioPaths.map(async (path) => ({ path, text: await readFile(path, "utf8") }))); const path = "PROJECTOR_SPEC/11-validation/testing-and-adversarial-evaluation.md"; return { scenarios, testing: { path, text: await readFile(path, "utf8") } }; }
const manifestFor = (inventory: Awaited<ReturnType<typeof deriveAcceptanceInventory>>, testSourceDigest: ReturnType<typeof hashFramedDomain>, testRef = "tests/public.test.ts#supported public behavior"): TraceabilityManifest => ({ version: 2, inventoryHash: traceabilityInventoryHash(inventory), entries: inventory.map((item) => { const entry = { ...item, publicFacade: "projector/testkit", testRef, testSourceDigest }; return { ...entry, mappingHash: traceabilityEntryHash(entry) }; }) });

describe("public release acceptance authority", () => {
  it("reads raw Vitest reporter output and rejects caller-created artifact claims", async () => { const root = await mkdtemp(join(tmpdir(), "traceability-")); try { const inventory = deriveAcceptanceInventory(await sources()); await mkdir(join(root, "tests")); const testSource = 'import { describe, it } from "vitest"; describe("supported public behavior", () => { it("passes", () => {}); });\n'; await writeFile(join(root, "tests/public.test.ts"), testSource); const sourceHash = hashFramedDomain("traceability-test-source", { path: "tests/public.test.ts", text: testSource }); const manifest = manifestFor(inventory, sourceHash); const reporterOutput = JSON.stringify({ success: true, numTotalTests: 1, numPassedTests: 1, testResults: [{ name: join(root, "tests/public.test.ts"), status: "passed", assertionResults: [{ ancestorTitles: ["supported public behavior"], fullName: "supported public behavior passes", status: "passed", title: "passes" }] }] }); const run = { reporterOutput, publicFacades: ["projector/testkit"] }; await expect(verifyTraceabilityManifest(manifest, inventory, { repositoryRoot: root, run })).resolves.toMatchObject({ verified: true }); await expect(verifyTraceabilityManifest(manifest, inventory, { repositoryRoot: root, run: { artifacts: [{ testRef: "tests/public.test.ts#supported public behavior", status: "passed", outputHash: hashFramedDomain("forged", "pass") }], publicFacades: ["projector/testkit"] } as never })).rejects.toThrow(/reporter|run evidence/iu); await expect(verifyTraceabilityManifest(manifest, inventory, { repositoryRoot: root, run: { ...run, reporterOutput: reporterOutput.replace('"status":"passed"', '"status":"failed"') } })).rejects.toThrow(/failed|passing|observed/iu); } finally { await rm(root, { recursive: true, force: true }); } });
  it("independently interprets raw fixture bytes and catches a shared seeded semantic contradiction", () => { const bytes = JSON.stringify({ id: "entity:right", kind: "concept", semanticHash: "semantic:right" }); const semanticDigest = hashFramedDomain("independent-release-semantics", { schemaId: "canonical-envelope-v2", runtimeLane: "node-json", entities: [{ id: "entity:right", kind: "concept", semanticHash: "semantic:right" }] }); const digest = hashFramedDomain("derived", "same"); const base = { rawDocuments: [{ path: "right.json", bytes }], schemaId: "canonical-envelope-v2" as const, runtimeLane: "node-json", locality: { changedEntityIds: ["entity:right"], recomputedEntityIds: ["entity:right"] }, evidenceIds: ["raw:schema"] }; expect(evaluateIndependentConformance({ ...base, clean: { derivedDigest: digest, semanticDigest: hashFramedDomain("wrong", "shared"), entityIds: ["entity:right"] }, incremental: { derivedDigest: digest, semanticDigest: hashFramedDomain("wrong", "shared"), entityIds: ["entity:right"] } }).passed).toBe(false); expect(evaluateIndependentConformance({ ...base, clean: { derivedDigest: digest, semanticDigest, entityIds: ["entity:right"] }, incremental: { derivedDigest: digest, semanticDigest, entityIds: ["entity:right"] } }).passed).toBe(true); });
  it("binds verified traceability and full benchmark results while refusing gate-waiving deviations", async () => { const inventory = deriveAcceptanceInventory(await sources()); const digest = hashFramedDomain("release", "fixture"); const traceability = manifestFor(inventory, digest); const traceabilityVerification = { verified: true as const, inventoryHash: traceability.inventoryHash, runEvidenceHash: digest, contentHash: hashFramedDomain("verified-traceability", { inventoryHash: traceability.inventoryHash, runEvidenceHash: digest, entries: traceability.entries.map(({ mappingHash }) => mappingHash) }) }; const raw = { id: "entity:a", kind: "concept", semanticHash: "semantic:a" }; const semanticDigest = hashFramedDomain("independent-release-semantics", { schemaId: "canonical-envelope-v2", runtimeLane: "node-json", entities: [raw] }); const conformance = evaluateIndependentConformance({ clean: { derivedDigest: digest, semanticDigest, entityIds: ["entity:a"] }, incremental: { derivedDigest: digest, semanticDigest, entityIds: ["entity:a"] }, rawDocuments: [{ path: "a.json", bytes: JSON.stringify(raw) }], schemaId: "canonical-envelope-v2", runtimeLane: "node-json", locality: { changedEntityIds: ["entity:a"], recomputedEntityIds: ["entity:a"] }, evidenceIds: ["raw:fixture"] }); const benchmark = { metrics: [{ id: "fixture", passed: true }], failures: [], releaseAllowed: true }; const input = { sourceRevision: "revision:fixture", worktreeDigest: digest, toolchainDigest: digest, buildDigest: digest, tarballDigest: digest, rawArtifacts: [{ id: "tarball", bytesHash: digest }], traceability, traceabilityVerification, inventory, benchmark, rebuildDigest: digest, conformance, deviations: [{ id: "deviation:none", severity: "note" as const, impact: "No release-impacting deviation", evidenceIds: ["gate:fixture"], waivedGateIds: [] }] }; expect(compileReleaseEvidence(input)).toMatchObject({ releaseAllowed: true, benchmark, contentHash: expect.stringMatching(/^sha256:v1:/u) }); expect(() => compileReleaseEvidence({ ...input, deviations: [{ ...input.deviations[0]!, waivedGateIds: ["benchmark"] }] })).toThrow(/cannot waive/iu); });
});
