import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import { hashFramedDomain } from "@projector/core";
import { compileReleaseEvidence, deriveAcceptanceInventory, evaluateIndependentConformance, traceabilityInventoryHash, validateTraceabilityManifest, type AcceptanceSource, type TraceabilityManifest } from "./release-acceptance.js";

const scenarioPaths = ["PROJECTOR_SPEC/12-delivery/acceptance-core.md", "PROJECTOR_SPEC/12-delivery/acceptance-relevance-and-identity.md", "PROJECTOR_SPEC/12-delivery/acceptance-representation.md", "PROJECTOR_SPEC/12-delivery/acceptance-architecture.md"];
async function sources() { const scenarios: AcceptanceSource[] = await Promise.all(scenarioPaths.map(async (path) => ({ path, text: await readFile(path, "utf8") }))); const path = "PROJECTOR_SPEC/11-validation/testing-and-adversarial-evaluation.md"; return { scenarios, testing: { path, text: await readFile(path, "utf8") } }; }
const manifestFor = (inventory: Awaited<ReturnType<typeof deriveAcceptanceInventory>>): TraceabilityManifest => ({ version: 1, inventoryHash: traceabilityInventoryHash(inventory), entries: inventory.map((item) => { const publicFacade = item.stratum === "scenario" ? "projector/cli" : "projector/testkit"; const testRef = `packages/testkit/src/release-acceptance.test.ts#${item.stratum}-public-stratum`; const id = `observation:${item.id}`; const status = "passed" as const; return { ...item, publicFacade, testRef, observation: { id, status, contentHash: hashFramedDomain("acceptance-observation", { id, status, publicFacade, testRef }) } }; }) });

describe("public release acceptance authority", () => {
  it("derives the exact 59/27/32 inventories and rejects skip, duplicate, relabel, and source drift", async () => { const inventory = deriveAcceptanceInventory(await sources()); expect(inventory.filter(({ stratum }) => stratum === "scenario")).toHaveLength(59); expect(inventory.filter(({ stratum }) => stratum === "property")).toHaveLength(27); expect(inventory.filter(({ stratum }) => stratum === "adversary")).toHaveLength(32); const manifest = manifestFor(inventory); expect(() => validateTraceabilityManifest(manifest, inventory)).not.toThrow(); expect(() => validateTraceabilityManifest({ ...manifest, entries: manifest.entries.slice(1) }, inventory)).toThrow(/count|incomplete/iu); expect(() => validateTraceabilityManifest({ ...manifest, entries: [...manifest.entries.slice(0, -1), manifest.entries[0]!] }, inventory)).toThrow(/duplicate|relabeled/iu); expect(() => validateTraceabilityManifest({ ...manifest, entries: manifest.entries.map((entry, index) => index === 0 ? { ...entry, title: "relabeled" } : entry) }, inventory)).toThrow(/stale/iu); expect(() => validateTraceabilityManifest({ ...manifest, entries: manifest.entries.map((entry, index) => index === 0 ? { ...entry, observation: { ...entry.observation, status: "skipped" as const } } : entry) }, inventory)).toThrow(/skipped|observation/iu); });
  it("uses an independent raw observation to catch a shared clean/incremental bug", () => { const wrong = hashFramedDomain("derived", "same-wrong"); const raw = hashFramedDomain("raw", "correct"); expect(evaluateIndependentConformance({ cleanDigest: wrong, incrementalDigest: wrong, rawObservationDigest: raw, evidenceIds: ["raw:schema"] })).toMatchObject({ passed: false, reasons: [expect.stringMatching(/shared|raw/iu)] }); });
  it("binds release evidence and refuses gate-waiving deviations or unauthenticated observations", async () => { const inventory = deriveAcceptanceInventory(await sources()); const traceability = manifestFor(inventory); const digest = hashFramedDomain("release", "fixture"); const conformance = evaluateIndependentConformance({ cleanDigest: digest, incrementalDigest: digest, rawObservationDigest: digest, evidenceIds: ["raw:fixture"] }); const input = { sourceRevision: "revision:fixture", worktreeDigest: digest, toolchainDigest: digest, buildDigest: digest, tarballDigest: digest, rawArtifacts: [{ id: "tarball", bytesHash: digest }], traceability, inventory, benchmarkPassed: true, rebuildDigest: digest, conformance, deviations: [{ id: "deviation:none", severity: "note" as const, impact: "No release-impacting deviation", evidenceIds: ["gate:fixture"], waivedGateIds: [] }] }; expect(compileReleaseEvidence(input)).toMatchObject({ releaseAllowed: true, contentHash: expect.stringMatching(/^sha256:v1:/u) }); expect(() => compileReleaseEvidence({ ...input, deviations: [{ ...input.deviations[0]!, waivedGateIds: ["benchmark"] }] })).toThrow(/cannot waive/iu); });
});
