import { createRequire as __projectorCreateRequire } from "node:module"; const require = __projectorCreateRequire(import.meta.url);
import {
  GitCommandError,
  analyzeCollectedLocalRepository,
  analyzeDocuments,
  analyzeJavaScript,
  analyzeLocalRepository,
  checkObservation,
  collectGitFacts,
  collectLocalRepositoryInputs,
  compileAuthenticatedAnalyzerTopology,
  compileEventContractTopology,
  compileRepositoryTopology,
  createTopologyRelevanceAdapter,
  createTopologyRelevanceQueryStatePort,
  detectMechanicalDivergences,
  finalizeGitFacts,
  hashJavaScriptSemantics,
  inventoryRepository,
  isExcludedInventoryPath,
  normalizeJavaScriptSemantics,
  observationFailure,
  observationGit,
  observationMap,
  readObservationFile
} from "../chunks/shared-IFURLTPX.js";
import "../chunks/shared-6VIFAIKJ.js";
export {
  GitCommandError,
  analyzeCollectedLocalRepository,
  analyzeDocuments,
  analyzeJavaScript,
  analyzeLocalRepository,
  checkObservation,
  collectGitFacts,
  collectLocalRepositoryInputs,
  compileAuthenticatedAnalyzerTopology,
  compileEventContractTopology,
  compileRepositoryTopology,
  createTopologyRelevanceAdapter,
  createTopologyRelevanceQueryStatePort,
  detectMechanicalDivergences,
  finalizeGitFacts,
  hashJavaScriptSemantics,
  inventoryRepository,
  isExcludedInventoryPath,
  normalizeJavaScriptSemantics,
  observationFailure,
  observationGit,
  observationMap,
  readObservationFile
};
